/**
 * Malay display copy for the admin System Manual.
 * Technical identifiers and source paths intentionally remain unchanged.
 */
export const MANUAL_MS_COPY: Record<string, string> = {
  "Finance Center 目前隐藏": "Finance Center disembunyikan buat masa ini",
  "查看 Deals P&L、Stock & Costing 与 Commission Ledger；Vehicle Model 只负责车型分组，每台实体库存用唯一 Number Plate 区分；所有 Finance Completed / Commission Paid 结算动作从 Task Inbox 执行。": "Lihat Deals P&L, Stock & Costing dan Commission Ledger; Vehicle Model hanya mengumpulkan jenis model, manakala setiap unit stok fizikal dibezakan oleh Number Plate yang unik; semua tindakan penyelesaian Finance Completed / Commission Paid dilaksanakan dari Task Inbox.",
  "Sales 没有 Finance Center 权限；只有 Bike Delivered 进入月度 P&L。旧库存缺少 number_plate 时必须人工补齐，系统不会自动把 chassis_number 当成车牌。": "Sales tidak mempunyai akses ke Finance Center; hanya Bike Delivered dimasukkan dalam P&L bulanan. Stok lama tanpa number_plate mesti dilengkapkan secara manual; sistem tidak akan menganggap chassis_number sebagai nombor plat secara automatik.",
  "当前阶段先验收贷款主流程，Finance Center 不显示在导航和 Role Access；功能代码与既有数据保留，下一阶段可恢复。": "Peringkat semasa mengutamakan penerimaan aliran pinjaman utama. Finance Center tidak dipaparkan dalam navigasi atau Akses Peranan; kod fungsi dan data sedia ada dikekalkan untuk dipulihkan pada peringkat seterusnya.",
  "下一阶段的成交、库存成本、收款、佣金和 Management P&L 模块。": "Modul peringkat seterusnya untuk jualan, kos inventori, terimaan, komisen dan P&L Pengurusan.",
  "当前 V1 暂不开放入口；代码与数据保留。": "Akses belum dibuka dalam V1 semasa; kod dan data dikekalkan.",
  "导航和 Role Access 均隐藏，待贷款主流程验收通过后再恢复。": "Navigasi dan Akses Peranan kedua-duanya disembunyikan sehingga aliran pinjaman utama lulus penerimaan.",
  "库存绑定使用 customer + vehicle_stock_reservations Firestore transaction，防止两台设备占用同一库存。": "Pengikatan stok menggunakan transaksi Firestore customer + vehicle_stock_reservations untuk menghalang dua peranti menempah stok yang sama.",
  "导航和 Role Access 均隐藏；恢复入口或部署新版应用前，必须先发布包含 vehicle_stock_reservations 的 Firestore Rules。": "Navigasi dan Akses Peranan disembunyikan; sebelum memulihkan akses atau melancarkan aplikasi baharu, terbitkan dahulu Firestore Rules yang mengandungi vehicle_stock_reservations.",
  "Finance Center 暂时隐藏；Tools 负责 reporting、tracking 和 audit；Rewards 负责激励结算视图。": "Finance Center disembunyikan buat sementara waktu; Tools mengurus pelaporan, penjejakan dan audit; Rewards mengurus paparan penyelesaian insentif.",
  "当前 V1 隐藏 Finance Center 导航和 Role Access 项目，先验收贷款主流程。既有 Deal、Stock、P&L 与 Vehicle Info 连接代码和数据全部保留，下一阶段恢复入口即可继续。": "V1 semasa menyembunyikan navigasi Finance Center dan item Akses Peranan untuk mengutamakan penerimaan aliran pinjaman. Semua kod dan data sedia ada bagi Deal, Stock, P&L serta sambungan Vehicle Info dikekalkan untuk peringkat seterusnya.",
  "当前 V1 隐藏 Finance Center 导航和 Role Access 项目，先验收贷款主流程。既有 Deal、Stock、P&L 与 Vehicle Info 连接代码和数据全部保留；库存预留通过 vehicle_stock_reservations 与 customer 在同一 Firestore transaction 提交，发布应用前必须先部署对应 Rules。": "V1 semasa menyembunyikan navigasi Finance Center dan Akses Peranan untuk mengutamakan aliran pinjaman utama. Kod dan data Deal, Stock, P&L serta Vehicle Info dikekalkan; tempahan stok dihantar bersama customer dalam transaksi Firestore yang sama melalui vehicle_stock_reservations, dan Rules berkaitan mesti digunakan sebelum aplikasi dilancarkan.",
  "当前 V1 隐藏导航与 Role Access 入口，代码和数据保留给下一阶段继续。": "V1 semasa menyembunyikan navigasi dan akses Akses Peranan; kod serta data dikekalkan untuk diteruskan pada peringkat seterusnya.",
  "系统基础资料、权限、通知关系和计算规则配置。": "Konfigurasi data asas sistem, kebenaran, hubungan pemberitahuan dan peraturan pengiraan.",
  "维护账号/Role Access、Notification Settings、Bank DB、Vehicle Categories、车型期限与生效价格、Brand Logos；Data Cleanup 只给 Super Admin debug。": "Selenggara akaun/Akses Peranan, Tetapan Pemberitahuan, Pangkalan Data Bank, Kategori Kenderaan, tempoh serta harga berkuat kuasa model dan Logo Jenama; Pembersihan Data hanya untuk nyahpepijat Pentadbir Super.",
  "Notification Settings 只给 Super Admin 查看触发条件、实际接收人、跳转位置和自动解除方式的关系。": "Tetapan Pemberitahuan hanya membenarkan Pentadbir Super melihat hubungan antara pencetus, penerima sebenar, destinasi dan cara penyelesaian automatik.",
  "Notification Settings": "Tetapan Pemberitahuan",
  "Super Admin 查看全部通知规则的触发条件、实际接收人优先级、跳转位置、解除方式和当前未解除数量。": "Pentadbir Super melihat pencetus, keutamaan penerima sebenar, destinasi, cara selesai dan jumlah aktif semasa untuk semua peraturan pemberitahuan.",
  "Data / Focus": "Data / Fokus",
  "Analytics helper, focus support, legacy secondary accent": "Pembantu analitis, sokongan fokus, loghat sekunder warisan",
  "Surface": "Permukaan",
  "Quiet panels, table hover, low-density background": "Panel senyap, tuding meja, latar belakang berketumpatan rendah",
  "Text": "Teks",
  "Primary text and high-contrast data": "Teks utama dan data kontras tinggi",
  "UI Body": "Badan UI",
  "Section Title": "Tajuk Bahagian",
  "KPI Number": "Nombor KPI",
  "Mono Data": "Data Mono",
  "Spacing": "Jarak",
  "Use 4px base rhythm. Dense tables stay tight; cards and sections breathe at 16-24px.": "Gunakan irama asas 4px. Meja padat kekal ketat; kad dan bahagian bernafas pada 16-24px.",
  "Radius": "Jejari",
  "`rounded-lg` controls, `rounded-xl` cards, `rounded-2xl` large manual sections only.": "Kawalan `bulat-lg`, kad `bulat-xl`, bahagian manual besar `bulat-2xl` sahaja.",
  "Controls": "Kawalan",
  "Inline controls can be 32px; normal buttons 40px; primary mobile actions 48px.": "Kawalan sebaris boleh menjadi 32px; butang biasa 40px; tindakan mudah alih utama 48px.",
  "Sidebar": "Bar sisi",
  "Compact rows, full-color 32px nav tiles, red pill selected state.": "Baris padat, jubin navigasi 32px berwarna penuh, keadaan pilihan pil merah.",
  "Charts": "Carta",
  "One primary chart per subject; details stay collapsed under the chart.": "Satu carta utama bagi setiap subjek; butiran kekal runtuh di bawah carta.",
  "Brand Red": "Jenama Merah",
  "Active nav, primary action, selected high-level state": "Nav aktif, tindakan utama, keadaan peringkat tinggi yang dipilih",
  "Brand Hover": "Jenama Hover",
  "Primary action hover / stronger emphasis": "Tindakan utama berlegar / penekanan yang lebih kuat",
  "Success": "Kejayaan",
  "Approved, completed, selected dropdown row, real on/off": "Diluluskan, selesai, baris lungsur yang dipilih, hidup/mati sebenar",
  "Warning": "Amaran",
  "Pending, due soon, needs attention": "Belum selesai, tidak lama lagi, memerlukan perhatian",
  "Error": "ralat",
  "Rejected, overdue, sync error, failed validation": "Ditolak, tertunggak, ralat penyegerakan, pengesahan gagal",
  "Raw Matches": "Padanan Mentah",
  "Dup Phones": "Telefon Dup",
  "Missions": "Misi",
  "Approvals": "Kelulusan",
  "Teams": "Pasukan",
  "Bank Records": "Rekod Bank",
  "Bank DB": "Bank DB",
  "Rules": "Peraturan",
  "WA Links": "Pautan WA",
  "Audit Logs": "Log Audit",
  "Type Scale": "Jenis Skala",
  "Micro labels, body, section title, KPI, hero metric. Avoid viewport-scaled font sizes.": "Label mikro, badan, tajuk bahagian, KPI, metrik wira. Elakkan saiz fon berskala port pandang.",
  "Apple-like Font System": "Sistem Font seperti Apple",
  "全站默认 font 已改成 Apple-like system stack：英文优先 San Francisco / SF Pro，中文优先 PingFang SC / Hiragino Sans GB；其他系统 fallback 到 Microsoft YaHei UI、Helvetica Neue、Arial、system-ui。数字/技术资料用 SF Mono fallback。": "Fon lalai seluruh tapak telah ditukar kepada susunan sistem seperti Apple: Keutamaan Bahasa Inggeris ialah San Francisco / SF Pro, keutamaan Bahasa Cina ialah PingFang SC / Hiragino Sans GB; sandaran sistem lain kepada Microsoft YaHei UI, Helvetica Neue, Arial, system-ui. Gunakan sandaran SF Mono untuk maklumat digital/teknikal.",
  "Ratio / Scale Rules": "Peraturan Nisbah/Skala",
  "System Manual": "Manual Sistem",
  "这页是 admin 使用说明书。它说明 Dr Racing Dashboard 的页面用途、角色权限、customer/loan 工作流、setting 维护、tools 报表、数据同步和 audit 逻辑。": "Halaman ini ialah manual pengguna pentadbir. Ia menerangkan tujuan halaman, kebenaran peranan, aliran kerja pelanggan/pinjaman, penyelenggaraan tetapan, laporan alatan, penyegerakan data dan logik audit Dr Racing Dashboard.",
  "Admin operating guide": "Panduan pengendalian pentadbir",
  "Customers": "Pelanggan",
  "Raw Leads": "Petunjuk Mentah",
  "潜在客户关系是风控对比": "Hubungan pelanggan yang berpotensi adalah perbandingan kawalan risiko",
  "集中比较贷款申请与 Lead Pool 的相同手机号、IC、银行户口和电邮；IC/户口列为高风险，并显示关联人员与负责人。": "Bandingkan nombor telefon mudah alih, IC, akaun bank dan e-mel yang sama antara permohonan pinjaman dan Lead Pool; IC/akaun disenaraikan sebagai berisiko tinggi, dan kakitangan yang berkaitan serta orang yang bertanggungjawab dipaparkan.",
  "Follow Up 是 sales 跟进台": "Susulan ialah meja susulan jualan",
  "Raw Customer 被 taken 后会进入 Follow Up。Sales 看自己的 lead，Admin/Super Admin 可以看全部 staff。": "Pelanggan Mentah akan memasuki Tindakan Susulan selepas diambil. Jualan boleh melihat petunjuk mereka sendiri, dan Pentadbir/Pentadbir Super boleh melihat semua kakitangan.",
  "Calendar 是日程视图": "Kalendar ialah paparan jadual",
  "Calendar 汇总 customer application、customer call-back、bank submission/decision/follow-up 和 Raw Customer follow-up due date；Super Admin 可在选定日期直接指派 task 给 staff。": "Kalendar meringkaskan permohonan pelanggan, panggilan balik pelanggan, penyerahan/keputusan/tindakan bank dan tarikh akhir susulan Pelanggan Mentah; Super Admin boleh terus memberikan tugas kepada kakitangan pada tarikh yang dipilih.",
  "Setting 是后台配置": "Tetapan ialah konfigurasi latar belakang",
  "Roles & Accounts、Role Access、Bank Database（含 Reject Reason Codes）、Vehicle Categories、Vehicle Info、Brand Logos 和 normalisation rules 都在 Setting 维护。": "Peranan & Akaun, Akses Peranan, Pangkalan Data Bank (termasuk Kod Sebab Tolak), Kategori Kenderaan, Maklumat Kenderaan, Logo Jenama dan peraturan normalisasi semuanya dikekalkan dalam Tetapan.",
  "Tools 是管理工具": "Alat adalah alat pengurusan",
  "Analytics、Missing Info Summary、Approval Workflow、WhatsApp Tools、Audit Log 统一在 Tools 里面。Sales 打开 Analytics 时只看自己的 personal analytics；Admin/Super Admin 看全局。": "Analitis, Ringkasan Maklumat Tiada, Aliran Kerja Kelulusan, Alat WhatsApp dan Log Audit disatukan dalam Alat. Apabila Jualan membuka Analitis, mereka hanya melihat analitis peribadi mereka sendiri; Admin/Super Admin melihat keadaan keseluruhan.",
  "1. Admin Quick Start": "1. Admin Mula Pantas",
  "新 admin 先理解这些核心规则，就能知道 dashboard 怎样运作。": "Pentadbir baharu perlu memahami peraturan teras ini terlebih dahulu untuk mengetahui cara papan pemuka berfungsi.",
  "Task Inbox 是每日工作入口": "Peti Masuk Tugas ialah pintu masuk ke kerja harian",
  "默认首页汇总当前 staff 今天要做什么：missing info、raw lead follow-up、bank pending action、reminder 和 custom mission progress。它只读现有数据，不创建独立 task record。": "Halaman utama lalai meringkaskan perkara yang dilakukan oleh kakitangan semasa hari ini: maklumat yang tiada, susulan petunjuk mentah, tindakan bank belum selesai, peringatan dan kemajuan misi tersuai. Ia hanya membaca data sedia ada dan tidak mencipta rekod tugas bebas.",
  "Staff View 是手机工作台": "Staff View ialah meja kerja mudah alih",
  "Staff View 面向手机和 sales 日常操作，只显示当前 staff 自己的 leads、due follow-up、customer tasks 和 scoped missions，并提供 Call、WhatsApp、Mark Contacted、Next Follow-up 大按钮。": "Paparan Kakitangan berorientasikan operasi harian pada telefon mudah alih dan jualan. Ia hanya memaparkan petunjuk kakitangan semasa sendiri, susulan wajar, tugas pelanggan dan misi skop, dan menyediakan butang besar untuk Panggilan, WhatsApp, Tandai Dihubungi dan Susulan Seterusnya.",
  "Customers 是主要工作台": "Pelanggan adalah meja kerja utama",
  "客户贷款申请、状态、final REJECT CODE、remarks、bank records、资料详情和 Add Customer 都从 Customers 处理。Show All 开启后可用 All Staff / Active staff dropdown 筛选 handler，并可继续叠加时间、状态和搜索条件。": "Permohonan pinjaman pelanggan, status, KOD TOLAK akhir, teguran, rekod bank, butiran profil dan Tambah Pelanggan semuanya dikendalikan daripada Pelanggan. Selepas Tunjukkan Semua dihidupkan, pengendali boleh ditapis mengikut lungsur turun Semua Kakitangan / Kakitangan Aktif, dan masa, status dan keadaan carian boleh terus ditindih.",
  "Raw Customers 是 lead database": "Pelanggan Mentah ialah pangkalan data utama",
  "TikTok/social lead 可用 CSV 或手动输入。Sales 新增的 lead 自动归属本人并设为 Private；Admin 可在 Duplicate Leads 案件删除错误名单，之后 CSV 自动排除同一来源记录。": "Prospek TikTok/sosial boleh diimport melalui CSV atau dimasukkan secara manual. Prospek baharu oleh Jualan menjadi Peribadi milik sendiri; Admin boleh memadam prospek yang salah dalam kes Prospek Pendua dan rekod sumber yang sama akan dikecualikan daripada import CSV seterusnya.",
  "Rewards 是奖励结算中心": "Ganjaran ialah pusat penyelesaian ganjaran",
  "Reward / Commission Center 是独立页面，内部有 Payout Center、Missions 和 Team Battle 三个 tab。Payout Center 看个人 commission、mission reward、leaderboard payout；Missions 管 custom missions；Team Battle 给 Super Admin 设两个 team 互相拼 sales。": "Pusat Ganjaran/Komisen ialah halaman bebas dengan tiga tab: Pusat Pembayaran, Misi dan Pertempuran Pasukan. Pusat Pembayaran melihat komisen peribadi, ganjaran misi dan pembayaran papan pendahulu; Misi menguruskan misi tersuai; Team Battle menyediakan dua pasukan untuk Super Admin bersaing untuk jualan.",
  "Sales Budget 是透明成本页": "Belanjawan Jualan ialah halaman kos yang telus",
  "Sales Budget 只读显示项目成本：MacBook、14 天人力、domain、server、AI service 和 skill value。它不写入 customer、audit、analytics 或 Firebase data。": "Bajet Jualan baca sahaja memaparkan kos projek: MacBook, buruh 14 hari, domain, pelayan, perkhidmatan AI dan nilai kemahiran. Ia tidak menulis data pelanggan, audit, analitis atau Firebase.",
  "Staff Mission 是待补资料": "Misi Kakitangan adalah maklumat yang perlu ditambah",
  "New/Used 和 Cash/Loan 不由 customer 填。系统会分配给 handler staff 补齐；浮动面板可最小化后再展开。": "Baru/Terpakai dan Tunai/Pinjaman tidak diisi oleh pelanggan. Sistem akan menyerahkannya kepada kakitangan pengendali untuk disiapkan; panel terapung boleh diminimumkan dan kemudian dikembangkan.",
  "Custom Mission 是 incentive": "Misi Tersuai ialah insentif",
  "Super Admin 可在 Rewards > Missions 创建 Top Sales、Fast Response、Raw Lead Conversion 任务，设置 target、reward、timeframe 和 scope，并先看当前 staff reference data。": "Pentadbir Super boleh membuat tugasan Jualan Teratas, Respons Pantas, Penukaran Petunjuk Mentah dalam Ganjaran > Misi, tetapkan sasaran, ganjaran, rangka masa dan skop serta lihat data rujukan kakitangan semasa dahulu.",
  "Audit Log 是追踪记录": "Log Audit ialah rekod jejak",
  "重要修改会记录 staff、role、IP、user agent、old value 和 new value。": "Pengubahsuaian penting direkodkan untuk kakitangan, peranan, IP, ejen pengguna, nilai lama dan nilai baharu.",
  "更换 Handler 仍仅限 Super Admin，会同时更新 handler name/role 并写入 Audit Log；Admin/Sales 的 Handler 保持只读。": "Penukaran Pengendali masih terhad kepada Pentadbir Super, akan mengemas kini nama/peranan pengendali dan menulisnya ke Log Audit; Pengendali Pentadbir/Jualan kekal baca sahaja.",
  "Raw Customers": "Pelanggan Mentah",
  "保存外部 lead 原始资料。": "Simpan bahan sumber utama luaran.",
  "Import TikTok CSV、手动新增、看 duplicate phones、看 raw lead 是否已匹配 Customers。": "Import TikTok CSV, tambah secara manual, semak telefon pendua dan semak sama ada petunjuk mentah telah sepadan dengan Pelanggan.",
  "Sales 新增自动成为自己的 Private lead，不进入其他人的 Lead Pool 或未分配名单；从 Duplicate Leads 删除的来源记录会在以后 CSV 导入时自动排除。": "Prospek baharu oleh Jualan menjadi prospek Peribadi milik sendiri dan tidak masuk ke Kumpulan Prospek orang lain atau senarai belum ditugaskan; rekod sumber yang dipadam daripada Prospek Pendua akan dikecualikan daripada import CSV akan datang.",
  "Potential Customer Relationships": "Hubungan Pelanggan Berpotensi",
  "把同一组潜在客户、lead 与贷款申请的所有相同资料集中成一个风控案件。": "Satukan semua data sepadan bagi kumpulan prospek, petunjuk dan permohonan pinjaman yang sama dalam satu kes kawalan risiko.",
  "按待处理、调查中、已结案、已隐藏推进；分配负责人、并排核对资料、记录评论；Admin 可从 Duplicate Leads 删除错误名单。": "Gerakkan kes melalui Belum Diproses, Dalam Siasatan, Ditutup dan Tersembunyi; tetapkan pemilik, bandingkan data sebelah menyebelah, catat ulasan; Admin boleh memadam prospek yang salah daripada Prospek Pendua.",
  "删除名单会写 Audit Log，并保存哈希导入指纹；之后 CSV 自动排除，手动新增仍沿用重复警告。": "Pemadaman prospek direkodkan dalam Log Audit dan cap jari import bercincang disimpan; CSV seterusnya mengecualikannya secara automatik, manakala penambahan manual masih menggunakan amaran pendua.",
  "Follow Up": "Susulan",
  "Task Inbox": "Peti Masuk Tugas",
  "当前 staff 的每日工作队列。": "Barisan kerja harian kakitangan semasa.",
  "查看 Missing Info、Raw Lead Follow Up、Bank Pending Action、Reminder、Custom Mission Progress，并跳到相关页面处理。": "Lihat Maklumat Hilang, Susulan Petunjuk Mentah, Tindakan Bank Belum Selesai, Peringatan, Kemajuan Misi Tersuai dan lompat ke halaman yang berkaitan untuk diproses.",
  "Admin 打开跨 Handler 的贷款任务时会自动切到 Show All 并直接打开 Application Detail；Task Inbox 不写入独立 task storage。": "Apabila Pentadbir membuka tugasan pinjaman milik Pengendali lain, sistem bertukar kepada Tunjukkan Semua dan terus membuka Butiran Permohonan; Peti Masuk Tugas tidak menulis ke storan tugas bebas.",
  "Staff View": "Pandangan Kakitangan",
  "手机优先的 staff 日常工作台。": "Meja kerja harian yang diutamakan mudah alih untuk kakitangan.",
  "只看自己的 leads、missions、follow-up 和 customer tasks；用大按钮 Call、WhatsApp、Mark Contacted、Next Follow-up 快速处理。": "Lihat sahaja petunjuk, misi, susulan dan tugas pelanggan anda; gunakan butang besar Panggil, WhatsApp, Tandai Dihubungi, Susulan Seterusnya untuk memprosesnya dengan cepat.",
  "不创建新数据源，所有动作仍写回 Raw Customer Follow Up / Customers / Rewards Missions / Missing Info Summary 现有资料。": "Tiada sumber data baharu dibuat, semua tindakan masih ditulis semula kepada Susulan Pelanggan Mentah / Pelanggan / Misi Ganjaran / Ringkasan Maklumat Hilang data sedia ada.",
  "贷款申请和客户跟进主页面。": "Permohonan pinjaman dan halaman utama susulan pelanggan.",
  "默认查看最近 30 天；点击 8 张 summary card 直接筛选状态。表格以图标区分 Cash/Loan；Finance Center 在 V1 隐藏期间，Cash 与 Loan 都使用已验收的 Submitted → Review → Docs → Result 核心流程，不显示隐藏模块的成交阶段。所有用户可双击复制表格资料，也可按 Enter/F2 进入获授权的编辑；Super Admin 可编辑全部客户。": "Secara lalai, 30 hari terakhir dipaparkan; klik 8 kad ringkasan untuk menapis status. Jadual membezakan Tunai/Pinjaman dengan ikon. Semasa Finance Center disembunyikan dalam V1, Tunai dan Pinjaman menggunakan aliran teras Submitted → Review → Docs → Result yang telah diterima tanpa memaparkan peringkat jualan modul tersembunyi. Semua pengguna boleh klik dua kali untuk menyalin; pengguna yang dibenarkan boleh menekan Enter/F2 untuk mengedit, dan Pentadbir Super boleh mengedit semua pelanggan.",
  "当前 V1 暂不开放入口；代码与数据保留。库存绑定使用 customer + vehicle_stock_reservations Firestore transaction，防止两台设备占用同一库存。": "Akses belum dibuka dalam V1 semasa; kod dan data dikekalkan. Pengikatan stok menggunakan transaksi Firestore customer + vehicle_stock_reservations supaya dua peranti tidak boleh menempah stok yang sama.",
  "案件级风控页：同一组关联人合并为一案；Sales 只读，Admin/Super Admin 只有成功载入远端 metadata 后才能修改。载入或保存失败时页面转为保护性只读；删除 Duplicate Lead 前先保存哈希导入指纹。": "Halaman risiko peringkat kes menggabungkan peserta berkaitan dalam satu kes. Jualan adalah baca sahaja; Pentadbir/Pentadbir Super hanya boleh mengubah selepas metadata jauh berjaya dimuatkan. Kegagalan muat atau simpan menukar halaman kepada baca sahaja perlindungan; cap jari import hash disimpan sebelum Duplicate Lead dipadam.",
  "当前 V1 隐藏入口；成交保存通过 Firestore transaction 原子更新 customer 与 vehicle_stock_reservations 库存锁，终止案件会释放锁并反转佣金。": "Akses V1 semasa disembunyikan; simpanan jualan mengemas kini customer dan kunci stok vehicle_stock_reservations secara atomik melalui transaksi Firestore, manakala kes tamat melepaskan kunci dan membalikkan komisen.",
  "Notification Center 是行动提醒": "Pusat Pemberitahuan ialah peringatan tindakan",
  "Header 铃铛显示 New raw lead assigned、Mission due soon、Bank Need More Info、Bank follow-up due、Customer call-back due、Custom Mission target reached、Rejected loan missing CODE 和 Internal comment tagged。New raw lead assigned 只在实际接手/转交时产生一次，handler 打开后标记 resolved，不会因资料重算再次出现。": "Loceng Pengepala memaparkan petunjuk mentah baharu yang ditetapkan, Misi akan tamat tidak lama lagi, Bank Memerlukan Maklumat Lanjut, Bank perlu membuat susulan, panggilan balik Pelanggan perlu dibayar, Sasaran Misi Tersuai tercapai, Pinjaman ditolak tiada KOD dan komen dalaman yang ditandai. Petunjuk mentah baharu yang diberikan hanya dijana sekali semasa pengambilalihan/pemindahan sebenar. Selepas pengendali dibuka, ia ditandakan diselesaikan dan tidak akan muncul lagi kerana pengiraan semula data.",
  "Internal Comment 是内部沟通": "Komen Dalaman ialah komunikasi dalaman",
  "每个 customer detail 有 Activity Thread。Admin 可直接 @Handler 指派补件或跟进行动，Staff 也可 @Admin/@Super Admin；被 tag 的人会在 Notification Center 与 Task Inbox 看到实际留言，打开或确认通知后解除该待办。": "Setiap butiran pelanggan mempunyai Thread Aktiviti. Pentadbir boleh terus @Handler untuk menetapkan tindakan dokumen atau susulan, manakala kakitangan juga boleh @Admin/@Super Admin; orang yang ditag akan melihat mesej sebenar dalam Pusat Pemberitahuan dan Peti Masuk Tugas, dan tugasan diselesaikan selepas pemberitahuan dibuka atau diakui.",
  "2. Page Map": "2. Peta Halaman",
  "每一个顶层 tab 的用途、谁会用、主要动作。": "Tujuan setiap tab peringkat atas, siapa yang akan menggunakannya, dan tindakan utamanya.",
  "Tab": "Tab",
  "Purpose": "Tujuan",
  "Main Actions": "Tindakan Utama",
  "Admin Notes": "Nota Pentadbir",
  "Taken raw lead 的跟进工作台。": "Bangku susulan untuk Diambil petunjuk mentah.",
  "更新 follow-up status、用 Tomorrow / 3 days / 7 days switch 设置 next follow-up、写 note，打开 WhatsApp Web。": "Kemas kini status susulan, gunakan suis Esok / 3 hari / 7 hari untuk menetapkan susulan seterusnya, tulis nota, buka WhatsApp Web.",
  "Sales 看自己的 taken leads；Admin/Super Admin 可以看全部。Next Follow Up 写入 raw lead record，Calendar 会自动显示。": "Jualan boleh melihat petunjuk mereka sendiri yang diambil; Admin/Super Admin boleh lihat kesemuanya. Susulan Seterusnya menulis rekod petunjuk mentah dan Kalendar akan dipaparkan secara automatik.",
  "Calendar": "Kalendar",
  "监督员工每日要执行的日程。": "Menyelia jadual harian pekerja.",
  "默认看 customer call-back、bank/raw lead follow-up 和管理层安排；Super Admin 在选定日期用 Assign Task 直接指派给 active staff。": "Secara lalai, ia melihat pada panggilan balik pelanggan, susulan petunjuk bank/mentah dan pengaturan pengurusan; Pentadbir Super menggunakan Tugasan Tugasan untuk menugaskan terus kepada kakitangan aktif pada tarikh yang dipilih.",
  "被指派员工会在 Calendar、Notification Center 和 Task Inbox 看到任务。标记 Completed 后通知自动 resolved；新增、完成、重开和删除动作写入 Audit Log。": "Pekerja yang ditugaskan akan melihat tugas dalam Kalendar, Pusat Pemberitahuan dan Peti Masuk Tugas. Selepas menandakan Selesai, pemberitahuan diselesaikan secara automatik; tindakan baharu, selesai, dibuka semula dan dipadam ditulis pada Log Audit.",
  "Setting": "Tetapan",
  "系统基础资料、权限和计算规则配置。": "Maklumat asas sistem, kebenaran dan konfigurasi peraturan pengiraan.",
  "维护账号/Role Access、Bank DB、Vehicle Categories、车型期限与生效价格、Brand Logos；Data Cleanup 只给 Super Admin debug。": "Mengekalkan Akses akaun/Peranan, Bank DB, Kategori Kenderaan, tempoh model dan harga berkesan, Logo Jenama; Pembersihan Data hanya untuk nyahpepijat Pentadbir Super.",
  "报表、missing info summary、approval、WhatsApp 和系统追踪工具。": "Laporan, ringkasan maklumat yang tiada, kelulusan, WhatsApp dan alat penjejakan sistem.",
  "看 Analytics/Missing Info Summary、管理 approval 和 WhatsApp tools、检查 Audit Log。": "Lihat Ringkasan Maklumat Analitis/Tiada, uruskan kelulusan dan alatan WhatsApp, semak Log Audit.",
  "Tools 是管理层看数据和查问题的地方。": "Alat ialah tempat pengurusan melihat data dan menyemak masalah.",
  "User": "pengguna",
  "当前登录 staff 的个人页面。": "Sedang log masuk ke halaman peribadi kakitangan.",
  "上传/移除 avatar，查看当前账号 name、role、email。": "Muat naik/alih keluar avatar dan lihat nama akaun semasa, peranan dan e-mel.",
  "Avatar 存在 role account，显示在 login、header 和 sidebar。": "Avatar mempunyai akaun peranan, yang dipaparkan dalam log masuk, pengepala dan bar sisi.",
  "完整系统说明书。": "Arahan sistem lengkap.",
  "理解 dashboard 如何工作、数据如何流动、每个配置影响哪里。": "Fahami cara papan pemuka berfungsi, cara data mengalir dan tempat setiap konfigurasi mempengaruhinya.",
  "给 admin onboarding 和日常排查使用。": "Digunakan untuk onboarding pentadbir dan penyelesaian masalah harian.",
  "3. Brand / UIUX Guide": "3. Panduan Jenama/UIUX",
  "Dr Racing Dashboard 的品牌哲学：Quiet Speed、Operational Luxury、Staff First、Evidence Over Decoration。界面要像高效率工作台，不像 marketing landing page。": "Falsafah jenama Dr Racing Dashboard: Kelajuan Tenang, Kemewahan Operasi, Kakitangan Didahulukan, Bukti Daripada Hiasan. Antara muka hendaklah seperti meja kerja kecekapan tinggi, bukan seperti halaman pendaratan pemasaran.",
  "Quiet Speed": "Kelajuan Tenang",
  "系统要让资料已经整理好，所以 staff 能快。速度来自清楚的任务、状态、筛选和下一步，不来自赛车装饰、大 hero 或视觉噪音。": "Sistem perlu mempunyai maklumat yang disusun, supaya kakitangan boleh melakukannya dengan cepat. Kelajuan datang daripada tugasan yang jelas, status, penapis dan langkah seterusnya, bukan daripada hiasan perlumbaan, wira besar atau bunyi visual.",
  "Operational Luxury": "Kemewahan Operasi",
  "高级感来自稳定 layout、清楚数字、干净图标、少解释、少跳动。它应该像专业工具，不像宣传页。": "Rasa mewah datang daripada susun atur yang stabil, nombor yang jelas, ikon bersih, kurang penjelasan dan kurang melompat. Ia sepatutnya kelihatan seperti alat profesional, bukan seperti halaman promosi.",
  "Staff First": "Kakitangan Didahulukan",
  "设计先服务销售和 admin 的重复工作：scan、filter、WhatsApp、follow up、补资料、查 bank status、改 record。减少培训成本。": "Reka bentuk ini mula-mula melaksanakan tugas berulang jualan dan pentadbir: imbasan, penapis, WhatsApp, susulan, tambah maklumat, semak status bank dan tukar rekod. Kurangkan kos latihan.",
  "Evidence Over Decoration": "Bukti Lebih Hiasan",
  "每个 card、badge、icon、chart 都要说明 status、priority、owner、action 或 performance。没有业务信息的装饰要移除。": "Setiap kad, lencana, ikon dan carta mesti menerangkan status, keutamaan, pemilik, tindakan atau prestasi. Hiasan tanpa maklumat perniagaan akan dialih keluar.",
  "这些配置会影响页面权限、贷款月供、selection controls、analytics、audit 和后续数据清理。": "Konfigurasi ini mempengaruhi kebenaran halaman, pembayaran bulanan pinjaman, kawalan pemilihan, analitik, audit dan pembersihan data seterusnya.",
  "Rewards": "Ganjaran",
  "奖励、commission、custom missions 和 team sales fight 结算视图。": "Ganjaran, komisen, misi tersuai dan paparan penyelesaian perjuangan jualan pasukan.",
  "看 mission reward、approved loan commission、leaderboard payout；管理 Custom Missions；Super Admin 设置 Team A / Team B、成员和赢家奖金。": "Lihat ganjaran misi, komisen pinjaman yang diluluskan, pembayaran papan pendahulu; menguruskan Misi Tersuai; Super Admin untuk menyediakan Pasukan A/Pasukan B, ahli dan bonus pemenang.",
  "Reward 数据从 Customers、Custom Missions、Approval Workflow 和 rewardTeams 推算；正式发放仍走 Approval Workflow。": "Data ganjaran dikira daripada Pelanggan, Misi Tersuai, Aliran Kerja Kelulusan dan Pasukan ganjaran; pengedaran rasmi masih melalui Aliran Kerja Kelulusan.",
  "Sales Budget": "Belanjawan Jualan",
  "对朋友展示透明项目成本。": "Tunjukkan kos projek yang telus kepada rakan.",
  "查看 MacBook、14 天时间成本、domain、server、AI service、skill value、首月成本、月费和第一年成本。": "Lihat MacBook, kos masa 14 hari, domain, pelayan, perkhidmatan AI, nilai kemahiran, kos bulan pertama, yuran bulanan dan kos tahun pertama.",
  "只读静态预算页，不接客户资料、audit log、analytics 或 Firebase 写入。": "Halaman belanjawan statik baca sahaja, tidak menerima penulisan data pelanggan, log audit, analitis atau Firebase.",
  "Tools": "Alatan",
  "Color Roles": "Peranan Warna",
  "Deep red 是 brand / active / primary operational action；emerald 是 success、selected 和真正 on/off；amber 是 pending；rose 是 error/reject；slate 是结构。": "Merah tua ialah tindakan operasi jenama / aktif / utama; zamrud ialah kejayaan, terpilih dan hidup/mati sebenar; ambar belum selesai; mawar adalah ralat/tolak; batu tulis adalah struktur.",
  "Two Icon Families": "Dua Keluarga Ikon",
  "Sidebar/mobile nav 用 colorful macOS tile PNG；页面内容、按钮、表格、状态用 flat line icon。不要把 tile icon 放进 dense table。": "Gunakan PNG jubin macOS berwarna-warni untuk Sidebar/nav mudah alih; gunakan ikon garis rata untuk kandungan halaman, butang, jadual dan keadaan. Jangan letakkan ikon jubin ke dalam jadual padat.",
  "Progressive Disclosure": "Pendedahan Progresif",
  "默认显示 current value、scope、priority 和 next action。raw detail、audit trail、advanced config、large table 默认收起。": "Nilai semasa, skop, keutamaan dan tindakan seterusnya dipaparkan secara lalai. Butiran mentah, jejak audit, konfigurasi lanjutan dan jadual besar ditutup secara lalai.",
  "High Signal Copy": "Salinan Isyarat Tinggi",
  "文案短、业务化、少解释。按钮说动作，empty state 说具体原因；不要把 UTM、localStorage、Firebase 这类技术词暴露给普通 staff。": "Salinan itu hendaklah pendek, berorientasikan perniagaan, dan menerangkan sedikit. Butang bercakap tentang tindakan, dan keadaan kosong bercakap tentang sebab tertentu; jangan dedahkan perkataan teknikal seperti UTM, localStorage dan Firebase kepada kakitangan biasa.",
  "Color System": "Sistem Warna",
  "Font / Ratio System": "Sistem Font / Nisbah",
  "Area": "Kawasan",
  "Brand Rule": "Peraturan Jenama",
  "Implementation Rule": "Peraturan Pelaksanaan",
  "Primary Color": "Warna Utama",
  "Deep red should carry Dr Racing identity and high-level active/primary operational actions.": "Merah pekat harus membawa identiti Dr Racing dan tindakan operasi aktif/utama peringkat tinggi.",
  "`red-800` / `red-900` for active sidebar, primary buttons, selected high-level state. Do not mix red and indigo randomly.": "`red-800` / `red-900` untuk bar sisi aktif, butang utama, keadaan aras tinggi yang dipilih. Jangan campurkan merah dan nila secara rawak.",
  "Secondary Color": "Warna Sekunder",
  "Indigo can remain as analytical/focus support, not the main brand color.": "Indigo boleh kekal sebagai sokongan analitikal/fokus, bukan warna jenama utama.",
  "Use indigo intentionally for analytics helpers, focus treatment, or legacy components until a full color migration is done.": "Gunakan indigo dengan sengaja untuk pembantu analitis, rawatan fokus atau komponen warisan sehingga pemindahan warna penuh dilakukan.",
  "KPI Title Badges": "Lencana Tajuk KPI",
  "All stat-card titles should use tinted semantic badges like Task Inbox titles, not pale standalone grey text.": "Semua tajuk kad statistik harus menggunakan lencana semantik berwarna seperti tajuk Peti Masuk Tugas, bukan teks kelabu kendiri pucat.",
  "Neutral=`bg-slate-100 text-slate-600`, pending=`amber`, success=`emerald`, danger/reject=`rose`, brand/primary=`red`. Apply this pattern across the site.": "Neutral=`bg-slate-100 text-slate-600`, belum selesai=`ambar`, success=`zamrud`, bahaya/tolak=`rose`, jenama/utama=`merah`. Gunakan corak ini di seluruh tapak.",
  "Font": "fon",
  "Use Apple OS-like system typography for a cleaner native-app feeling, including Chinese text.": "Gunakan tipografi sistem seperti Apple OS untuk perasaan aplikasi asli yang lebih bersih, termasuk teks bahasa Cina.",
  "Default sans stack starts with `-apple-system`, `SF Pro`, then `PingFang SC` / `Hiragino Sans GB` for Chinese; mono starts with `SF Mono`.": "Timbunan sans lalai bermula dengan `-apple-system`, `SF Pro`, kemudian `PingFang SC` / `Hiragino Sans GB` untuk bahasa Cina; mono bermula dengan `SF Mono`.",
  "Ratio": "Nisbah",
  "Keep the interface on a compact 4px rhythm with predictable type and control scale.": "Kekalkan antara muka pada irama 4px padat dengan jenis dan skala kawalan yang boleh diramal.",
  "Spacing 4/8/12/16/24; radius 8/12/16; controls 32/40/48; type 10/12/14/24/56.": "Jarak 4/8/12/16/24; jejari 8/12/16; kawalan 32/40/48; taip 10/12/14/24/56.",
  "Surfaces": "Permukaan",
  "Quiet white/slate surfaces keep dense business data readable.": "Permukaan putih/batu yang senyap memastikan data perniagaan padat boleh dibaca.",
  "Analytics should answer business questions without chart noise.": "Analitis harus menjawab soalan perniagaan tanpa bunyi carta.",
  "One main chart per subject. Big number only for the main answer. Show sample badges for small denominators and total rows before details.": "Satu carta utama bagi setiap subjek. Nombor besar sahaja untuk jawapan utama. Tunjukkan lencana sampel untuk penyebut kecil dan jumlah baris sebelum butiran.",
  "Copywriting": "Copywriting",
  "Copy should be short, concrete, and business-facing.": "Salinan hendaklah pendek, konkrit, dan menghadap perniagaan.",
  "Use business terms: Customer, Lead, Loan, Vehicle, Bank, Follow Up. Avoid technical field names, UTM language, and multi-sentence UI explanations.": "Gunakan istilah perniagaan: Pelanggan, Lead, Pinjaman, Kenderaan, Bank, Susulan. Elakkan nama medan teknikal, bahasa UTM dan penjelasan UI berbilang ayat.",
  "Mobile": "Mudah alih",
  "Mobile is for field work, not full admin configuration.": "Mudah alih adalah untuk kerja lapangan, bukan konfigurasi pentadbir penuh.",
  "Prioritize Task Inbox, Follow Up, Loan Applications, Lead Pool, Calendar. Keep buttons large and summaries compact.": "Utamakan Peti Masuk Tugas, Susulan, Permohonan Pinjaman, Kumpulan Utama, Kalendar. Pastikan butang besar dan ringkasan padat.",
  "Accessibility": "Kebolehcapaian",
  "Premium UI still needs visible affordance.": "UI Premium masih memerlukan kemampuan yang boleh dilihat.",
  "Light/Dark Mode 都使用语义色映射：blue/indigo=info/focus、amber=pending、purple=follow-up、emerald=success、rose/red=reject/critical、slate=structure；不要硬编码浅色背景或低对比文字。": "Mod Cerah/Gelap kedua-duanya menggunakan pemetaan warna semantik: biru/indigo=info/fokus, ambar=pending, ungu=susulan, zamrud=kejayaan, mawar/merah=menolak/kritikal, batu tulis=struktur; jangan kod keras latar belakang terang atau teks kontras rendah.",
  "Cards": "Kad",
  "Cards are for repeated items, KPI tiles, modals, drawers, and framed tools.": "Kad adalah untuk item berulang, jubin KPI, modal, laci dan alatan berbingkai.",
  "业务 card、panel、sidebar 和 header 使用透明 outline 的 borderless surface；用 spacing、背景和 `rounded-xl` 建立层次。输入框、focus state 和必要分隔线仍需清楚。": "Kad perniagaan, panel, bar sisi dan pengepala menggunakan permukaan tanpa sempadan dengan garis besar telus; gunakan jarak, latar belakang dan `bulat-xl` untuk membuat hierarki. Kotak input, keadaan fokus dan pemisah yang diperlukan masih perlu jelas.",
  "Use controls by meaning, not by style.": "Gunakan kawalan dengan makna, bukan dengan gaya.",
  "`ToggleSwitch` only for true on/off. `ToggleOptionGroup` is the conventional single-select dropdown: current value + chevron, active row emerald + check.": "`ToggleSwitch` hanya untuk hidup/mati benar. `ToggleOptionGroup` ialah lungsur turun pilihan tunggal konvensional: nilai semasa + chevron, baris aktif zamrud + semak.",
  "Tables": "Meja",
  "Tables are the main working surface, not secondary decoration.": "Meja adalah permukaan kerja utama, bukan hiasan sekunder.",
  "Stable row height, sortable useful columns, action-only columns unsorted, long lists virtualized, existing data edited only by double-click or explicit edit affordance.": "Ketinggian baris yang stabil, lajur berguna boleh diisih, lajur tindakan sahaja tidak diisih, senarai panjang dimayakan, data sedia ada diedit hanya dengan klik dua kali atau kemampuan edit eksplisit.",
  "Analytics": "Analitis",
  "Icon-only buttons need title/aria-label。重要状态不能只靠颜色；即使 card outline 透明，keyboard focus、input boundary 和 active state 仍必须可见。": "Butang ikon sahaja memerlukan tajuk/label aria. Keadaan penting tidak boleh bergantung pada warna sahaja; walaupun garis besar kad telus, fokus papan kekunci, sempadan input dan keadaan aktif mesti masih kelihatan.",
  "Design debt to clean next": "Reka bentuk hutang untuk membersihkan seterusnya",
  "Keep semantic status colors consistent in both themes; update ICONS.md for the PNG nav icon family; continue checking focus/input visibility on borderless surfaces; keep System Manual and design.md in sync when brand rules change.": "Pastikan warna status semantik konsisten dalam kedua-dua tema; kemas kini ICONS.md untuk keluarga ikon nav PNG; teruskan menyemak keterlihatan fokus/input pada permukaan tanpa sempadan; pastikan Manual Sistem dan reka bentuk.md selari apabila peraturan jenama berubah.",
  "4. Roles & Visibility": "4. Peranan & Keterlihatan",
  "Role": "Peranan",
  "Default View": "Paparan Lalai",
  "Can Do": "Boleh Buat",
  "Important Limit": "Had Penting",
  "Super Admin": "Super Admin",
  "默认 Show All，也可切指定 staff。": "Lalai ialah Tunjukkan Semua, anda juga boleh menentukan kakitangan.",
  "管理所有 customers、Public/Private leads、settings、Role Access、roles、tags、bank database、CODE issues 和 staff 风控关系。": "Urus semua pelanggan, petunjuk Awam/Swasta, tetapan, Akses Peranan, peranan, teg, pangkalan data bank, isu KOD dan perhubungan kawalan risiko kakitangan.",
  "能看到全部 staff 的 Private lead 与关联记录；指定 staff 的通知只在切到该 staff scope 时出现。": "Petunjuk peribadi dan rekod berkaitan semua kakitangan boleh dilihat; pemberitahuan untuk kakitangan yang ditentukan hanya akan muncul apabila bertukar kepada skop kakitangan.",
  "Admin": "Admin",
  "通常按账号或业务权限看数据。": "Data biasanya dilihat berdasarkan kebenaran akaun atau perniagaan.",
  "处理申请、看 analytics/mission、协助 bank application follow-up。": "Memproses permohonan, menyemak analitik/misi, dan membantu dengan susulan permohonan bank.",
  "不应直接维护 Super Admin 专属配置。": "Konfigurasi khusus Super Admin tidak boleh dikekalkan secara langsung.",
  "Sales": "Jualan",
  "默认看自己的 applications、taken/private leads、missions、风险关系和 personal analytics。": "Secara lalai, lihat aplikasi anda sendiri, petunjuk yang diambil/peribadi, misi, perhubungan risiko dan analitik peribadi.",
  "用 CSV 或手动输入新增自己的 Private lead、跟进自己的客户、完成自己 handler mission。": "Gunakan CSV atau input manual untuk menambah petunjuk peribadi anda sendiri, membuat susulan ke atas pelanggan anda dan menyelesaikan misi pengendali anda.",
  "不能浏览其他人的 Private lead；只有当记录与自己的 Private lead 在 phone、IC、bank account 或 email 匹配时，才会在 Potential Customer Relationships 显示关联记录。": "Anda tidak boleh menyemak imbas petunjuk Peribadi orang lain; hanya apabila rekod sepadan dengan petunjuk Peribadi anda sendiri dalam telefon, IC, akaun bank atau e-mel, rekod yang berkaitan akan dipaparkan dalam Perhubungan Pelanggan Berpotensi.",
  "Logged out": "Log keluar",
  "没有 dashboard 操作入口。": "Tiada kemasukan operasi papan pemuka.",
  "只能访问 public routes，例如 /wa redirect、/customer-intake、/s short link。": "Hanya laluan awam, seperti /wa redirect, /customer-intake, /s short link, boleh diakses.",
  "员工用 Email + Password 登录 Firebase Auth；Remember me 控制登录持久化和 email 记忆。Role Account 只保存角色、状态和 Auth 映射。": "Pekerja menggunakan E-mel + Kata Laluan untuk log masuk ke Firebase Auth; Ingat saya mengawal ketekunan log masuk dan ingatan e-mel. Akaun Peranan hanya menyimpan peranan, keadaan dan pemetaan Auth.",
  "Super Admin 可在 Setting &gt; Roles &amp; Accounts &gt; Role Access 调整页面入口；页面内查看、编辑、导出和资料范围仍按角色规则执行。Finance Center 仅限 Super Admin；Audit Log 对 Sales 固定关闭；Data Export 默认关闭，但可按资料集开放。停用 Role Account 会同时停用对应 Firebase Auth 用户并撤销现有登录 token。": "Pentadbir Super boleh melaraskan pintu masuk halaman melalui Tetapan > Peranan & Akaun > Akses Peranan; paparan, suntingan, eksport dan skop data dalam halaman masih tertakluk pada peraturan peranan. Pusat Kewangan hanya untuk Pentadbir Super; Log Audit sentiasa ditutup untuk Jualan; Eksport Data ditutup secara lalai tetapi boleh dibuka mengikut set data. Menyahaktifkan Akaun Peranan juga akan menyahaktifkan pengguna Firebase Auth yang sepadan dan membatalkan token log masuk sedia ada.",
  "5. Customer And Loan Workflow": "5. Aliran Kerja Pelanggan Dan Pinjaman",
  "从 lead 到 customer application，再到 bank application 和 final loan status 的完整路径。": "Laluan lengkap dari petunjuk kepada permohonan pelanggan kepada permohonan bank dan status pinjaman akhir.",
  "Raw lead arrives": "Plumbum mentah tiba",
  "TikTok/social lead 用 CSV 或手动输入；Sales 新增自动保存为本人 Private lead，保留 channel、lead ID、phone、email、status。": "Gunakan CSV atau input manual untuk TikTok/pemimpin sosial; Jualan yang baru ditambah akan disimpan secara automatik sebagai petunjuk peribadi anda sendiri dan saluran, ID petunjuk, telefon, e-mel dan status akan dikekalkan.",
  "Cross-check": "Semak silang",
  "Potential Customer Relationships 用 IC、phone、bank account、email 比较 lead/application，标出关系与风险等级；员工可评论或隐藏已确认提醒。": "Perhubungan Pelanggan Berpotensi menggunakan IC, telefon, akaun bank dan e-mel untuk membandingkan petunjuk/aplikasi dan menandakan perhubungan dan tahap risiko; pekerja boleh mengulas atau menyembunyikan peringatan yang disahkan.",
  "Customer ready": "Pelanggan sedia",
  "客户准备申请 loan 后，Sales 手动 Add Customer 或分享 customer intake link。": "Selepas pelanggan bersedia untuk memohon pinjaman, Jualan menambah Pelanggan secara manual atau berkongsi pautan pengambilan pelanggan.",
  "NEW application": "Permohonan BARU",
  "系统创建 NEW application，handler 默认当前 staff，New/Used 和 Cash/Loan 留空。": "Sistem mencipta aplikasi BARU, pengendali lalai kepada kakitangan semasa, dan Baru/Terpakai dan Tunai/Pinjaman dibiarkan kosong.",
  "Staff mission": "Misi kakitangan",
  "负责 staff 登录后看到待补 New/Used 和 Cash/Loan 任务。": "Selepas kakitangan yang bertanggungjawab log masuk, mereka akan melihat tugasan Baru/Terpakai dan Tunai/Pinjaman untuk diselesaikan.",
  "Bank records": "Rekod bank",
  "Admin 在 customer detail 里维护多间 bank application record 和 bank decision。": "Pentadbir mengekalkan beberapa rekod permohonan bank dan keputusan bank secara terperinci pelanggan.",
  "Final status": "Status akhir",
  "最终 loan status 在 Customers 更新。REJECT 时每一个纯数字 CODE 都要各自匹配一条 explanation；2 个 CODE 显示 2 个解释，依此类推。": "Akhirnya status pinjaman dikemas kini dalam Pelanggan. Apabila TOLAK, setiap KOD angka semata-mata mesti sepadan dengan penjelasan; 2 KOD memaparkan 2 penjelasan, dan seterusnya.",
  "6. Customer Detail Drawer": "6. Laci Butiran Pelanggan",
  "打开 customer row 后，右侧 detail drawer 是单个 customer ID 的完整资料中心。": "Selepas membuka baris pelanggan, laci butiran di sebelah kanan ialah pusat maklumat lengkap untuk ID pelanggan tunggal.",
  "Basic & Personal Info": "Maklumat Asas & Peribadi",
  "Share Link、Add Customer 和 Application Detail 会先按购买方式分流。客户地址分为 Permanent Address (IC) 和 Resident Address；Resident Address 可点击「Same as Permanent Address (IC)」复制。Cash 只收姓名、电话、IC、IC 自动识别的 Date of Birth、Email（可选）和两个地址；Loan 才追加 Gender、种族、婚姻、住房与居住年数。Share Link / Customer Application Form 的 Loan Gender 必填，Add Customer 可先建立未完整记录，但 Notify Admin 前必须补齐。DOB 可复制但不手动编辑。旧记录的 full_address 继续作为 Permanent Address (IC)，不会自动填充 Resident Address。": "Share Link, Tambah Pelanggan dan Butiran Permohonan dibahagikan mengikut kaedah pembelian. Alamat pelanggan dibahagikan kepada Alamat Tetap (IC) dan Alamat Kediaman; Alamat Kediaman boleh disalin melalui butang Sama seperti Alamat Tetap (IC). Tunai mengumpulkan nama, telefon, IC, Tarikh Lahir yang dikesan daripada IC, e-mel pilihan dan kedua-dua alamat; Pinjaman menambah jantina, bangsa, perkahwinan, perumahan dan tempoh menetap. Jantina wajib untuk Pinjaman dalam Share Link / Borang Permohonan Pelanggan. Tambah Pelanggan boleh mencipta rekod belum lengkap, tetapi Jantina mesti dilengkapkan sebelum Maklumkan Pentadbir. DOB boleh disalin tetapi tidak diedit. full_address rekod lama kekal sebagai Alamat Tetap (IC) dan tidak mengisi Alamat Kediaman secara automatik.",
  "Vehicle & Purchase": "Kenderaan & Belian",
  "保存 primary motorcycle、fallback choices、New/Used、Cash/Loan。Primary Vehicle 是 Loan 时另外显示员工内部的 Motor Selling Price、Deposit 和 Total Cash Price；Race 是客户种族资料。": "Simpan motosikal utama, pilihan sandaran, Baharu/Terpakai dan Tunai/Pinjaman. Apabila Kenderaan Utama ialah Pinjaman, Harga Jualan Motor, Deposit dan Jumlah Harga Tunai dalaman kakitangan turut dipaparkan; Bangsa ialah maklumat bangsa pelanggan.",
  "Employment Details": "Butiran Pekerjaan",
  "保存 Gross/Net Monthly Salary、公司、职位、工作年数、地址和 office phone；Share Link、Add Customer 与 Application Detail 都不再收集 Work Hours，旧记录仍兼容保留。": "Simpan Gaji Kasar/Bersih Bulanan, syarikat, jawatan, tempoh bekerja, alamat dan telefon pejabat. Share Link, Tambah Pelanggan dan Butiran Permohonan tidak lagi mengumpul Waktu Kerja; rekod lama kekal serasi.",
  "Emergency Contacts": "Kenalan Kecemasan",
  "保存两个 emergency contact 的姓名、关系、地址和电话。": "Simpan nama, perhubungan, alamat dan nombor telefon dua kenalan kecemasan.",
  "Status & Preferences": "Status & Keutamaan",
  "保存 call availability、Bank/Cash salary method、salary bank（只在 Bank 时）、preferred motorcycle、loan tenure、remarks、final status、primary final reject CODE 和全部 final reject CODE chips。贷款银行仍由 Super Admin 在 Bank Database 流程决定。": "Simpan ketersediaan panggilan, kaedah gaji Bank/Tunai, bank gaji (hanya apabila Bank), motosikal pilihan, tempoh pinjaman, catatan, status akhir, KOD penolakan akhir utama dan semua cip KOD penolakan akhir. Bank pembiayaan masih dipilih oleh Super Admin dalam aliran Pangkalan Data Bank.",
  "File / Document Checklist": "Senarai Semak Fail/Dokumen",
  "追踪 IC、Payslip 和 Supporting Doc；不再显示 Guarantor Doc。公开 Customer Intake 可由客户上传 IC、Payslip / Payment Proof 和可选 Supporting Doc（每个最多 10MB），文件会进入同一份 Application Detail / Task Inbox 清单并自动变 Received。员工也可继续从每个文件项上传；没有文件时只手动切 Missing 或 Not Required。": "Jejak IC, Payslip dan Dokumen Sokongan; Dokumen Penjamin tidak lagi dipaparkan. Pengambilan Pelanggan awam membenarkan pelanggan memuat naik IC, Slip Gaji / Bukti Bayaran dan Dokumen Sokongan pilihan (maksimum 10MB setiap fail); fail masuk ke senarai yang sama dalam Butiran Permohonan / Peti Masuk Tugasan dan menjadi Diterima secara automatik. Kakitangan masih boleh memuat naik daripada setiap item; tanpa fail, hanya Hilang atau Tidak Diperlukan dipilih secara manual.",
  "Bank Applications": "Permohonan Bank",
  "每个 customer 可有多间 bank application；Admin 可记录多个 reject CODE，Reject Reason 会自动关联 Error Code Database，没有 CODE 时可手动填写原因。": "Setiap pelanggan boleh mempunyai berbilang permohonan bank; Pentadbir boleh merekodkan berbilang KOD penolakan, Sebab Penolakan dipautkan secara automatik daripada Pangkalan Data Kod Ralat, dan sebab boleh dimasukkan secara manual apabila tiada KOD.",
  "Activity Thread": "Benang Aktiviti",
  "Customer 内部沟通集中在 detail drawer：Admin 可 @Handler，Staff 可 @Admin/@Super Admin；实际留言会进入被 tag 员工的 Notification Center 与 Task Inbox，员工打开或确认后解除待办。Enter 提交，Shift+Enter 换行。": "Komunikasi dalaman pelanggan tertumpu pada laci butiran: Pentadbir boleh @Handler dan kakitangan boleh @Admin/@Super Admin; mesej sebenar akan masuk ke Pusat Pemberitahuan dan Peti Masuk Tugas kakitangan yang ditag, dan tugasan diselesaikan selepas kakitangan membuka atau mengakuinya. Enter untuk menghantar dan Shift+Enter untuk baris baharu.",
  "Copy & Edit Gestures": "Salin & Edit Gerak Isyarat",
  "Loan Applications 表格与申请详情默认不暴露 input。表格保留双击复制、三击编辑；Application Detail 改为单击复制、双击编辑。Super Admin 可编辑全部客户资料，当前 Handler 只可编辑自己负责的资料与备注；其他用户仍为只读复制。Handler 更换仍仅限 Super Admin，银行流程字段仍由 Admin/Super Admin 管理。": "Jadual Loan Applications dan Butiran Permohonan tidak memaparkan input secara lalai. Jadual mengekalkan klik dua kali untuk menyalin dan klik tiga kali untuk mengedit; Butiran Permohonan menggunakan satu klik untuk menyalin dan klik dua kali untuk mengedit. Pentadbir Super boleh mengedit semua data pelanggan, manakala Pengendali semasa hanya boleh mengedit data dan catatan pelanggan yang ditugaskan kepadanya; pengguna lain kekal salin sahaja. Penukaran Pengendali masih terhad kepada Pentadbir Super, manakala medan aliran bank kekal diurus oleh Pentadbir/Pentadbir Super.",
  "7. Bank Application Manual": "7. Manual Permohonan Bank",
  "Bank Application 是 customer 底下的独立银行申请记录，不等于 final loan status。": "Permohonan Bank ialah rekod permohonan bank bebas di bawah pelanggan, yang tidak sama dengan status pinjaman akhir.",
  "Status": "Status",
  "Meaning": "Maknanya",
  "Fields Admin Should Update": "Fields Admin Harus Kemas Kini",
  "Draft": "Draf",
  "资料准备中，还没提交银行。": "Maklumat sedang disediakan dan masih belum diserahkan kepada pihak bank.",
  "Preparation Notes。": "Nota Persediaan.",
  "Submitted": "diserahkan",
  "已经提交给银行。": "Sudah diserahkan kepada bank.",
  "Submitted time、Submission Notes。": "Masa dihantar, Nota Penyerahan.",
  "Pending Review": "Menunggu Semakan",
  "银行处理中或等待回复。": "Bank sedang memproses atau menunggu balasan.",
  "Follow Up Notes、next action、Bank Follow Up Date。": "Nota Susulan, tindakan seterusnya, Tarikh Susulan Bank.",
  "Need More Info": "Perlukan Maklumat Lanjut",
  "银行要求补资料。": "Bank memerlukan maklumat tambahan.",
  "Reason、Next Action、Bank Follow Up Date，隐藏 reject fields。": "Sebab, Tindakan Seterusnya, Tarikh Susulan Bank, sembunyikan medan penolakan.",
  "Rejected": "ditolak",
  "银行拒绝这间 bank application。": "Bank menolak permohonan bank ini.",
  "多个 Reject CODE 会自动关联 Reject Reason；没有 CODE 时手动填写 Reject Reason，并记录 Bank Notes 与 Next Action。": "Berbilang KOD Tolak memautkan Sebab Tolak secara automatik; apabila tiada KOD, masukkan Sebab Tolak secara manual dan rekodkan Nota Bank serta Tindakan Seterusnya.",
  "Approved": "Diluluskan",
  "银行批准申请。": "Bank meluluskan permohonan.",
  "Offer amount、interest、tenure、monthly installment、decision notes。": "Jumlah tawaran, faedah, tempoh, ansuran bulanan, nota keputusan.",
  "Cancelled": "Dibatalkan",
  "申请取消。": "Permohonan untuk pembatalan.",
  "Cancellation Reason。": "Sebab Pembatalan.",
  "8. Setting Manual": "8. Manual Tetapan",
  "Setting 是系统行为的配置中心。改这里会影响 Customers、Tools、selection controls、analytics 和 audit。": "Tetapan ialah pusat konfigurasi untuk tingkah laku sistem. Menukar ini akan menjejaskan Pelanggan, Alat, kawalan pemilihan, analitis dan audit.",
  "Setting Group": "Kumpulan Tetapan",
  "Impact": "Kesan",
  "Roles & Accounts": "Peranan & Akaun",
  "Super Admin/Admin/Sales account、email、Firebase Auth user 创建/映射、Firebase password reset、status、staff avatar upload/remove、default avatar library upload/remove；每张 default avatar 只能分配给一个 staff。": "Akaun Super Admin/Admin/Jualan, e-mel, penciptaan/pemetaan pengguna Firebase Auth, tetapan semula kata laluan Firebase, status, muat naik/alih keluar avatar kakitangan, muat naik/alih keluar pustaka avatar lalai; setiap avatar lalai hanya boleh diberikan kepada seorang kakitangan.",
  "影响 Email 登录匹配、staff scope、mission visibility、权限文案，以及 Customers / Raw Customers / Follow Up / Calendar 的 staff avatar badge。": "Mempengaruhi padanan log masuk E-mel, skop kakitangan, keterlihatan misi, penulisan salinan kebenaran dan lencana avatar kakitangan untuk Pelanggan / Pelanggan Mentah / Susulan / Kalendar.",
  "Role Access": "Akses Peranan",
  "两类设置共用一个页面但保持各自权限规则；Finance Center 仅限 Super Admin，Audit Log 对 Sales 固定关闭，Data Export 可按资料集开放。": "Kedua-dua tetapan berkongsi satu halaman tetapi mengekalkan peraturan akses masing-masing; Pusat Kewangan hanya untuk Pentadbir Super, Log Audit sentiasa ditutup untuk Jualan, dan Eksport Data boleh dibuka mengikut set data.",
  "影响 desktop/mobile navigation 和 page entry；不取代页面内 action/data-scope 规则。Firestore 只允许 Super Admin 修改此配置。": "Mempengaruhi navigasi desktop/mudah alih dan kemasukan halaman; tidak menggantikan peraturan tindakan/skop data dalam halaman. Firestore hanya membenarkan Pentadbir Super mengubah suai konfigurasi ini.",
  "Bank Database": "Pangkalan Data Bank",
  "Bank name、active status switch、uploaded icon crop/adjust；同页维护 Final loan rejected CODE 对应 issue 和 customer request。": "Nama bank, suis status aktif, potong/laras ikon yang dimuat naik; mengekalkan KOD pinjaman Akhir ditolak pada halaman yang sama sepadan dengan keluaran dan permintaan pelanggan.",
  "影响 personal bank selection、bank application selection、bank icon display、Customers final REJECT CODE 和 Tools > Analytics rejected CODE reporting；icon 保存为 128x128 PNG。": "Mempengaruhi pemilihan bank peribadi, pemilihan aplikasi bank, paparan ikon bank, KOD TOLAK akhir Pelanggan dan Alat > Analitis menolak pelaporan KOD; ikon disimpan sebagai PNG 128x128.",
  "Vehicle Categories": "Kategori Kenderaan",
  "维护 Moped、Maxi Scooter、Big Bike、Super Bike 等分类、CC 提示、2–7 年默认最长 tenure，以及按 effective date 生效的 category rate history。": "Kekalkan kategori seperti Moped, Skuter Maxi, Basikal Besar, Basikal Super, gesaan CC, tempoh maksimum lalai 2-7 tahun dan sejarah kadar kategori berkuat kuasa mengikut tarikh berkuat kuasa.",
  "Monthly Plan 会按申请/价格日期选取当时有效利率；车型自己的 max tenure 优先，否则使用 category default。": "Pelan Bulanan akan memilih kadar faedah efektif semasa berdasarkan tarikh permohonan/harga; tempoh maksimum model itu sendiri diutamakan, jika tidak lalai kategori akan digunakan.",
  "Vehicle Info": "Maklumat Kenderaan",
  "Motorcycle aliases、category、cash price、loan amount、deposit、finance profile、editable formula、monthly preview；每个车型可保存 effective-dated price history 和 2–7 年 max tenure。": "Alias motosikal, kategori, harga tunai, jumlah pinjaman, deposit, profil kewangan, formula boleh edit, pratonton bulanan; setiap model boleh menyimpan sejarah harga bertarikh berkesan dan tempoh maksimum 2–7 tahun.",
  "Duplicate Models 区集中显示全部重复车型组。Super Admin 选择一条 Master 并确认 Merge 后，系统保留 Master、补齐其空白资料、删除其余重复记录，并把相关 Loan Application 车型名称统一成 Master；也可多选车型批量设置 category/tenure，缺失车型可从提示 chip 补入 catalog。": "Bahagian Model Pendua memusatkan semua kumpulan model pendua. Selepas Pentadbir Super memilih satu rekod Master dan mengesahkan Merge, sistem mengekalkan Master, mengisi data kosongnya daripada rekod pendua, memadam rekod lain dan menyatukan nama kenderaan Loan Application berkaitan kepada nama Master. Pentadbir Super juga boleh memilih berbilang model untuk menetapkan kategori/tempoh secara pukal, manakala model yang hilang boleh ditambah ke katalog daripada cip cadangan.",
  "Brand Logos": "Logo Jenama",
  "上传品牌图后选择 square/wide、缩放、位置和背景色。": "Selepas memuat naik imej jenama anda pilih segi empat sama/lebar, skala, kedudukan dan warna latar belakang.",
  "Square 保存为 256×256 PNG，wide 保存为 384×128 PNG，并上传 Firebase Storage 供车型和界面共用。": "Square disimpan sebagai 256×256 PNG, lebar disimpan sebagai 384×128 PNG dan dimuat naik ke Firebase Storage untuk perkongsian antara model kereta dan antara muka.",
  "Data Cleanup": "Pembersihan Data",
  "隐藏的 Super Admin debug 区，用来维护 Vehicle、marketing、bank_reject、application_status_reason normalisation rules。": "Kawasan nyahpepijat Super Admin yang tersembunyi digunakan untuk mengekalkan peraturan normalisasi Kenderaan, pemasaran, bank_reject, application_status_reason.",
  "影响 parent/category reporting，避免同义字造成 analytics drift；普通 Setting 操作不需要打开。": "Menjejaskan pelaporan ibu bapa/kategori untuk mengelakkan drift analitik yang disebabkan oleh sinonim; operasi Tetapan biasa tidak perlu dihidupkan.",
  "9. Tools And Rewards Manual": "9. Manual Alatan Dan Ganjaran",
  "Tools 负责 reporting、tracking 和 audit；Rewards 独立负责 commission、leaderboard 和 team bonus 结算视图。": "Alat bertanggungjawab untuk melaporkan, menjejak dan mengaudit; Ganjaran bertanggungjawab secara bebas untuk komisen, papan kepimpinan dan pandangan penyelesaian bonus pasukan.",
  "整页使用 Daily / Weekly / Overall 报表模式和统一日期范围；Standard / Compare 设定直接显示在顶部筛选卡。主次 KPI、申请状态、提交趋势、申请明细，以及下方 NRIC、raw lead、车型、营销、运营和 final REJECT CODE 深入分析均使用同一套筛选数据。Sales 只看 personal analytics。": "Seluruh halaman menggunakan mod laporan Harian / Mingguan / Keseluruhan dan julat tarikh bersepadu; tetapan Standard / Banding dipaparkan terus dalam kad penapis atas. KPI utama dan sekunder, status permohonan, trend penghantaran, rekod permohonan serta analisis lanjut NRIC, prospek mentah, model, pemasaran, operasi dan KOD TOLAK akhir semuanya menggunakan data ditapis yang sama. Jualan hanya melihat analitik peribadi.",
  "Analytics Chart / Bar": "Carta/Bar Analitis",
  "Application Status 在卡片右上角独立切换 Comparison、Share 和 Performance；Marketing、Vehicle Demand、Customer Profile、Operations、Lead Pool 使用同一个 Tab 面板原地切换，一次只显示一个模块。当前模块在右上角独立切换并记住 Bar、Donut、Combo、Trend。": "Status Permohonan menukar Perbandingan, Bahagian dan Prestasi secara berasingan di penjuru kanan atas kad; Pemasaran, Permintaan Kenderaan, Profil Pelanggan, Operasi dan Kumpulan Prospek bertukar dalam panel Tab yang sama dan hanya satu modul dipaparkan pada satu masa. Modul semasa menukar serta mengingati Bar, Donat, Kombo dan Trend secara berasingan di penjuru kanan atas.",
  "Missing Info Summary": "Ringkasan Maklumat Tiada",
  "查谁改了什么、什么时候改、old/new value、IP 和 user agent。排查数据被改动时先看这里。": "Semak siapa yang menukar apa, bila, nilai lama/baru, IP dan ejen pengguna. Semak di sini dahulu apabila data penyelesaian masalah telah diubah suai.",
  "Notification Center": "Pusat Pemberitahuan",
  "Header 铃铛与 Task Inbox 使用同一单一员工 scope，所以 badge 是该员工 scope 的 unread，不等于 task card 数。Super Admin 默认只看自己，选择 Staff Filter 后只代看该员工；明确 staff recipient 优先于 role。handler 打开 New raw lead assigned 后会 resolved，Super Admin 代看不会替 handler 解决。customer/loan notification 会打开 drawer，comment tag 会滚到 Activity Thread。": "Loceng Pengepala dan Peti Masuk Tugas menggunakan skop seorang kakitangan yang sama, jadi lencana menunjukkan belum dibaca bagi skop kakitangan itu dan tidak sama dengan bilangan kad tugasan. Pentadbir Super melihat tugas sendiri secara lalai dan hanya melihat tugas kakitangan yang dipilih melalui Penapis Kakitangan; penerima kakitangan yang dinyatakan mengatasi peranan. Tugasan Petunjuk Mentah Baharu diselesaikan apabila pengendali membukanya, dan pandangan wakil Pentadbir Super tidak menyelesaikannya bagi pengendali. Pemberitahuan pelanggan/pinjaman membuka laci, manakala tag komen menatal ke Thread Aktiviti.",
  "Timeframe Filter": "Penapis Jangka Masa",
  "Analytics 顶部日期面板按 Daily、Weekly、Overall 显示对应预设，支持 Custom start/end date，并明确显示实际生效范围。": "Panel tarikh di bahagian atas Analitik memaparkan pratetap mengikut Harian, Mingguan dan Keseluruhan, menyokong tarikh mula/tamat tersuai dan menunjukkan julat berkuat kuasa sebenar dengan jelas.",
  "Reporting Source": "Sumber Pelaporan",
  "Analytics 使用 cleaned application data、raw lead data、WhatsApp click data 和 Setting normalisation rules。": "Analitis menggunakan data aplikasi yang dibersihkan, data petunjuk mentah, data klik WhatsApp dan Menetapkan peraturan normalisasi.",
  "10. Sales Budget Manual": "10. Manual Belanjawan Jualan",
  "Sales Budget 是项目透明成本页面，方便把投入和持续成本讲清楚。": "Belanjawan Jualan ialah halaman kos projek yang telus yang memudahkan untuk menerangkan dengan jelas pelaburan dan kos berterusan.",
  "Cost Group": "Kumpulan Kos",
  "Tools 内保留 missing info 的 assigned/pending/completed summary，只看 missing New/Used 和 Cash/Loan，不管理 custom missions。": "Ringkasan maklumat hilang yang diberikan/tertunda/selesai disimpan dalam Alat, hanya Baharu/Terpakai yang tiada dan Tunai/Pinjaman dilihat dan misi tersuai tidak diurus.",
  "Reward / Commission Center": "Pusat Ganjaran/Komisen",
  "独立 Rewards 页面内部有 Payout Center、Missions 和 Team Battle 三个 tab。Payout Center 看 mission reward、top sales bonus、approved loan commission、fast response bonus、monthly leaderboard payout 和 Team Battle bonus；Missions 管理 custom missions；正式发放仍走 Approval Workflow。": "Halaman Ganjaran bebas mempunyai tiga tab: Pusat Pembayaran, Misi dan Pertempuran Pasukan. Pusat Pembayaran melihat ganjaran misi, bonus jualan tertinggi, komisen pinjaman yang diluluskan, bonus respons pantas, pembayaran papan pendahulu bulanan dan bonus Pertempuran Pasukan; Misi menguruskan misi tersuai; bayaran rasmi masih melalui Aliran Kerja Kelulusan.",
  "Team Battle": "Pertempuran Pasukan",
  "Team Battle 是 Reward / Commission Center 内的另一个 tab。Super Admin 可设置最多两个 active teams、成员和每位赢家成员的额外 RM。系统用本月 approved loan count 计算团队输赢；平手或双方 0 approved 不派赢家 team bonus。": "Team Battle ialah tab lain dalam Pusat Ganjaran / Komisen. Super Admin boleh menyediakan dua pasukan aktif, ahli dan tambahan RM untuk setiap ahli yang menang. Sistem ini menggunakan kiraan pinjaman yang diluluskan bulan ini untuk mengira menang atau kalah pasukan; tidak akan ada bonus pasukan untuk seri atau 0 yang diluluskan oleh kedua-dua pihak.",
  "Approval Workflow": "Aliran Kerja Kelulusan",
  "Sales discount、special loan case、cash discount、extra commission、mission reward 和 sick leave request 集中提交和审核；sick leave 会自动记录当前 staff、支持 0.5 days 和 MC PDF/image attachment；所有决定都会写 audit。": "Diskaun jualan, kes pinjaman khas, diskaun tunai, komisen tambahan, ganjaran misi dan permintaan cuti sakit dikemukakan dan disemak secara berpusat; cuti sakit secara automatik akan merekodkan kakitangan semasa, sokongan 0.5 hari dan lampiran MC PDF/imej; semua keputusan akan ditulis untuk diaudit.",
  "WhatsApp Tools": "Alat WhatsApp",
  "管理同一份 Default Message；Raw Customer WhatsApp 和新建 tracking link 默认都会使用它，current staff 会自动写入 tracking。": "Uruskan Mesej Lalai yang sama; WhatsApp Pelanggan Mentah dan pautan penjejakan baharu akan menggunakannya secara lalai, dan kakitangan semasa akan ditulis secara automatik ke dalam penjejakan.",
  "Audit Log": "Log Audit",
  "只读计算，不创建 billing record。": "Pengiraan baca sahaja, tiada rekod pengebilan dibuat.",
  "Bill": "Bil",
  "显示可每月 charge 的基础月费：Domain / 12、Server per month、Founder / builder time 每月 4 天。": "Memaparkan yuran bulanan asas yang boleh dicaj setiap bulan: Domain / 12, Pelayan sebulan, Pengasas / masa pembina 4 hari sebulan.",
  "只读计算，不创建 invoice、payment 或 accounting record。": "Pengiraan baca sahaja, tiada invois, pembayaran atau rekod perakaunan dibuat.",
  "Skill Value": "Nilai Kemahiran",
  "AI skill、marketing skill、sales skill、data analytic skill 的贡献说明。": "Penerangan sumbangan kemahiran AI, kemahiran pemasaran, kemahiran jualan, kemahiran analisis data.",
  "没有直接 receipt，所以不计入 direct cash total。": "Tiada resit langsung, jadi ia tidak termasuk dalam jumlah tunai langsung.",
  "11. Tracking And Public Link Rules": "11. Peraturan Penjejakan Dan Pautan Awam",
  "Dashboard 有 customer intake、WhatsApp tracking 和 Raw Customer WhatsApp quick open。用途不同，不能混在一起。": "Papan pemuka mempunyai pengambilan pelanggan, penjejakan WhatsApp dan WhatsApp Pelanggan Mentah dibuka pantas. Mereka mempunyai kegunaan yang berbeza dan tidak boleh dicampur bersama.",
  "Link Type": "Jenis Pautan",
  "What It Shows": "Apa yang Ditunjukkannya",
  "Data Rule": "Peraturan Data",
  "Hardware": "Perkakasan",
  "MacBook Pro M4 Max 64GB/1TB 参考价格。": "Harga rujukan MacBook Pro M4 Max 64GB/1TB.",
  "静态参考值，正式报价前应重新检查市场价格。": "Nilai rujukan statik, harga pasaran hendaklah disemak semula sebelum sebut harga rasmi.",
  "Time Cost": "Kos Masa",
  "用 RM8,000 previous salary / 22 working days x 14 days 计算 builder 机会成本。": "Kira kos peluang pembina menggunakan RM8,000 gaji sebelumnya / 22 hari bekerja x 14 hari.",
  "不写入 staff payroll，只作为项目成本解释。": "Tidak termasuk dalam senarai gaji kakitangan, hanya dijelaskan sebagai kos projek.",
  "Recurring Cost": "Kos Berulang",
  "Domain yearly、server monthly、AI service monthly，并显示 first-month 和 year-one totals。": "Domain tahunan, pelayan bulanan, perkhidmatan AI bulanan dan memaparkan jumlah bulan pertama dan tahun satu.",
  "URL": "URL",
  "Stored Data": "Data Tersimpan",
  "Customer Intake": "Pengambilan Pelanggan",
  "/customer-intake 或 /s/{code}": "/pengambilan pelanggan atau /s/{kod}",
  "让 customer 自己填写申请资料。": "Biarkan pelanggan mengisi sendiri maklumat permohonan.",
  "创建 NEW application，写入 customer_intake_tracking 和 ci_utm_*。": "Buat aplikasi BAHARU dan tulis customer_intake_tracking dan ci_utm_*.",
  "WhatsApp Tracking": "Penjejakan WhatsApp",
  "/wa?... 或 /s/{code}": "/wa?... atau /s/{kod}",
  "包装 WhatsApp URL，记录点击来源后跳去 WhatsApp。": "Balut URL WhatsApp, rekod sumber klik dan lompat ke WhatsApp.",
  "默认使用 WhatsApp Tools 的 Default Message，并写入 WhatsAppTrackingClick，自动记录当前 staff。": "Secara lalai, Mesej Lalai Alat WhatsApp digunakan dan ditulis ke WhatsAppTrackingClick untuk merekodkan kakitangan semasa secara automatik.",
  "Raw Lead WhatsApp": "WhatsApp Lead Mentah",
  "Raw Customers phone double click": "Klik dua kali telefon Pelanggan Mentah",
  "用 WhatsApp Tools 默认 message 直接打开 raw lead WhatsApp。": "Gunakan mesej lalai Alat WhatsApp untuk terus membuka WhatsApp utama mentah.",
  "把 public lead 标记为 taken lead，记录 owner/time/status，进入 Follow Up；不创建 customer，不写 tracking click。": "Tandai petunjuk awam sebagai petunjuk, rekod pemilik/masa/status, dan masukkan Tindakan Susulan; jangan buat pelanggan dan jangan tulis klik penjejakan.",
  "Short Link": "Pautan Pendek",
  "/s/{code}": "/s/{kod}",
  "短码会映射到完整 target URL。": "Kod pendek memetakan ke URL sasaran penuh.",
  "同一套 short link mechanism 可服务 customer intake 和 WhatsApp tracking。": "Mekanisme pautan pendek yang sama melayani pengambilan pelanggan dan penjejakan WhatsApp.",
  "12. Data Storage And Sync": "12. Penyimpanan Dan Penyegerakan Data",
  "系统先保证本机可用，再尝试同步 Firebase。": "Sistem terlebih dahulu memastikan bahawa mesin tempatan tersedia sebelum cuba menyegerakkan Firebase.",
  "Notifications": "Pemberitahuan",
  "系统根据当前 dashboard data 和 comment tag 生成、去重并保存 notification。Raw lead assignment 以接手/转交事件产生；handler read 后 resolved，release 后移除，重新接手才产生新事件。": "Sistem menjana, menyahduplikasi dan menyimpan pemberitahuan berdasarkan data papan pemuka semasa dan teg ulasan. Tugasan petunjuk mentah dijana dengan mengambil alih/serah tugas; pengendali diselesaikan selepas dibaca, dialih keluar selepas keluaran, dan peristiwa baharu dijana hanya apabila ia diambil alih semula.",
  "Production data": "Data pengeluaran",
  "系统不再自动 seed demo customer。资料来自实际 intake、手动新增、Raw Lead 流程或受控 Excel missing-only import。": "Sistem ini tidak lagi membekalkan pelanggan demo secara automatik. Data datang daripada pengambilan sebenar, penambahan manual, proses Raw Lead atau Excel terkawal hilang-satunya import.",
  "Audit append": "Lampiran audit",
  "重要变更同时 append audit log，记录变更来源。": "Perubahan penting dilampirkan pada log audit untuk merekodkan sumber perubahan.",
  "13. Source Code Map": "13. Peta Kod Sumber",
  "Admin 不需要改代码，但这张表说明每个功能大概由哪个 module 负责，方便交接给 developer。": "Admin tidak perlu menukar kod, tetapi jadual ini menunjukkan modul mana yang bertanggungjawab untuk setiap fungsi untuk memudahkan penyerahan kepada pembangun.",
  "What It Does": "Apa yang Dilakukan",
  "Main File": "Fail Utama",
  "React state": "Keadaan bertindak balas",
  "用户操作后先更新当前页面状态，UI 立即反映。": "Selepas pengguna beroperasi, status halaman semasa dikemas kini terlebih dahulu dan UI mencerminkannya serta-merta.",
  "localStorage cache": "Cache storan setempat",
  "启动时先从本机 cache 显示数据；Firebase 不可用时仍能继续使用。": "Data dipaparkan daripada cache tempatan semasa permulaan; ia boleh terus digunakan apabila Firebase tidak tersedia.",
  "Queued Firebase save": "Simpanan Firebase beratur",
  "如果 Firebase configured，修改会在 250ms 内合并后顺序保存，pagehide 时会 flush pending edit，避免旧 async save 覆盖新数据。": "Jika Firebase dikonfigurasikan, pengubahsuaian akan digabungkan dan disimpan secara berurutan dalam masa 250ms dan pengeditan yang belum selesai akan dipadamkan semasa sembunyi halaman untuk mengelakkan simpanan async lama daripada menimpa data baharu.",
  "Sync badge": "Segerakkan lencana",
  "Header 对 staff 显示产品化状态：已同步、缓存中、本地模式、同步中、同步失败；Firebase 只留在内部技术说明。": "Pengepala memaparkan status pengeluaran untuk kakitangan: disegerakkan, dicache, mod setempat, disegerakkan, disegerakkan gagal; Firebase hanya meninggalkan penerangan teknikal dalaman.",
  "Reminder dates": "Tarikh peringatan",
  "Customer call-back 和 bank follow-up 存在 customer/bank records；Calendar、Task Inbox 和 Notifications 只读取这些日期。": "Rekod pelanggan/bank wujud untuk panggilan balik Pelanggan dan susulan bank; Kalendar, Peti Masuk Tugas dan Pemberitahuan hanya membaca tarikh ini.",
  "执行监督月历：call-back、bank/raw lead follow-up、Super Admin 指派任务与完成状态；指派任务同步进入 Notification Center 和 Task Inbox。": "Laksanakan kalendar penyeliaan: panggil balik, susulan petunjuk bank/mentah, tugasan yang diberikan oleh Pentadbir Super dan status penyelesaian; tugas yang diberikan disegerakkan ke dalam Pusat Pemberitahuan dan Peti Masuk Tugas.",
  "Roles、Bank DB、Vehicle Categories、车型价格/期限、Brand Logos、motor catalog 和 normalisation rules。": "Peranan, Bank DB, Kategori Kenderaan, harga/tempoh model, Logo Jenama, katalog motor dan peraturan penormalan.",
  "配置 desktop/mobile 页面入口、自动 fallback 与固定敏感页面限制；账号 status 另行同步 Firebase Auth suspension。": "Konfigurasikan pintu masuk halaman desktop/mudah alih, sandaran automatik dan tetapkan sekatan halaman sensitif; status akaun disegerakkan secara berasingan dengan penggantungan Firebase Auth.",
  "Vehicle Rules": "Peraturan Kenderaan",
  "分类默认 tenure、effective rate、车型 effective price/deposit history、model override 和 bulk tenure/category。": "Kategori lalai kepada tempoh, kadar berkesan, model sejarah harga/deposit berkesan, penggantian model dan tempoh/kategori pukal.",
  "Brand Logo Storage": "Storan Logo Jenama",
  "裁切后的 square/wide PNG 上传和共用。": "PNG persegi/lebar dipotong untuk memuat naik dan berkongsi.",
  "Motor Price Seed": "Benih Harga Motor",
  "从 motor price.xlsx 融合进 Vehicle Information 的车型价格表。": "Senarai harga model digabungkan ke dalam Maklumat Kenderaan daripada harga motor.xlsx.",
  "Tools Analytics": "Analitis Alat",
  "App Shell": "App Shell",
  "登录、routing、state、localStorage/Firebase sync、audit handlers。": "Log masuk, penghalaan, negeri, penyegerakan localStorage/Firebase, pengendali audit.",
  "每次只显示一个员工的 tasks 和 notifications。Super Admin 默认只看自己的任务，并可用带头像的 Staff Filter 选择 Active staff；没有 All Staff 任务汇总。Super Admin 专属 Staff Attention & Progress 会横向比较 Active Admin/Sales 的逾期、待办、进行中工作量和平均 Mission 进度，按异常优先排序。点员工后进入 Focus 模式，只保留该员工卡片并切换到其任务；Show all staff 返回全部比较和 Super Admin 自己的队列。未指定 owner 的 Admin Team 工作只属于 Admin scope，不会进入 Super Admin 默认队列；切到具体 Admin 时才显示。": "Setiap masa hanya tugasan dan pemberitahuan seorang kakitangan dipaparkan. Pentadbir Super melihat tugas sendiri secara lalai dan boleh memilih kakitangan Aktif melalui Penapis Kakitangan beravatar; tiada ringkasan tugasan Semua Kakitangan. Perhatian & Kemajuan Kakitangan khas Pentadbir Super membandingkan tunggakan, tindakan, beban kerja aktif dan purata kemajuan Misi bagi Pentadbir/Jualan Aktif serta menyusun keadaan luar biasa dahulu. Memilih kakitangan memasuki mod Fokus yang hanya mengekalkan kad kakitangan itu dan menukar ke tugasan mereka; Tunjukkan semua kakitangan mengembalikan perbandingan penuh dan baris gilir Pentadbir Super sendiri. Kerja Pasukan Pentadbir tanpa pemilik hanya berada dalam skop Pentadbir dan tidak masuk ke baris gilir lalai Pentadbir Super; ia dipaparkan selepas memilih Pentadbir tertentu.",
  "Mobile-first staff 工作台，聚合自己的 leads、missions、customer tasks，并提供 Call/WhatsApp/Mark Contacted/Next Follow-up 大按钮。": "Meja kerja kakitangan yang mengutamakan mudah alih, mengagregatkan petunjuk, misi, tugas pelanggannya sendiri dan menyediakan butang Panggilan/WhatsApp/Tandakan Dihubungi/Seterusnya yang besar.",
  "客户列表、8 个可点击 summary/filter cards、Add Customer、customer intake link。默认只看最近 30 天；Total card 看全部状态，其余 7 张 card 直接筛对应状态，不再显示重复 status tab bar。列表和 cards 共用 staff/time scope。": "Senarai pelanggan, 8 kad ringkasan/penapis boleh klik, Tambah Pelanggan, pautan pengambilan pelanggan. Secara lalai, hanya 30 hari terakhir dilihat; Jumlah kad memaparkan semua status, dan baki 7 kad disaring terus untuk status yang sepadan, dan bar tab status pendua tidak lagi dipaparkan. Senarai dan kad berkongsi kakitangan/skop masa.",
  "Detail Drawer": "Laci Perincian",
  "单个 customer 的完整资料、bank application、payslip、internal comment/activity thread、status edit。": "Maklumat lengkap pelanggan tunggal, permohonan bank, slip gaji, ulasan dalaman/benang aktiviti, edit status.",
  "外部 lead database、CSV/manual entry、public/private/taken scope、creator ownership、duplicate phones、raw/customer matching，以及已删除来源记录的 CSV 导入排除。": "Pangkalan data prospek luaran, kemasukan CSV/manual, skop awam/peribadi/diambil, pemilikan pencipta, telefon pendua, padanan prospek/pelanggan dan pengecualian import CSV untuk rekod sumber yang dipadam.",
  "案件级风控页：同一组关联人合并为一案；Admin 可删除 Duplicate Leads 中的错误名单并保存哈希导入指纹，避免之后 CSV 重新加入。": "Halaman kawalan risiko peringkat kes: kumpulan orang berkaitan digabungkan menjadi satu kes; Admin boleh memadam prospek yang salah dalam Prospek Pendua dan menyimpan cap jari import bercincang supaya CSV tidak menambahnya semula.",
  "Taken raw lead 的 sales 跟进台、status、Tomorrow / 3 days / 7 days next follow-up switches、note、WhatsApp Web button。": "Meja susulan jualan mentah yang diambil, status, Esok / 3 hari / 7 hari suis susulan seterusnya, nota, butang Web WhatsApp.",
  "Daily/Weekly/Overall 模式、顶部统一日期/对比面板、主次 KPI、卡内状态视图、自适应趋势、申请明细，以及一次显示一个模块的深入分析 Tab 面板。": "Mod Harian/Mingguan/Keseluruhan, panel tarikh/perbandingan bersepadu di atas, KPI utama dan sekunder, paparan status dalam kad, trend adaptif, rekod permohonan serta panel Tab analisis lanjut yang memaparkan satu modul pada satu masa.",
  "Reward Center": "Pusat Ganjaran",
  "Payout Center、Missions 和 Team Battle tabs；显示 mission reward、approved loan commission、leaderboard payout、custom mission builder 和 team bonus 的独立结算视图。": "Tab Pusat Pembayaran, Misi dan Pertempuran Pasukan; menunjukkan paparan pengebilan berasingan untuk ganjaran misi, komisen pinjaman yang diluluskan, pembayaran papan pendahulu, pembina misi tersuai dan bonus pasukan.",
  "透明成本页，展示 MacBook、人力、domain、server、AI service、skill value、首月总成本、月费和第一年成本。": "Halaman kos telus yang memaparkan MacBook, tenaga kerja, domain, pelayan, perkhidmatan AI, nilai kemahiran, jumlah kos bulan pertama, yuran bulanan dan kos tahun pertama.",
  "Sales/Admin/Super Admin 的折扣、特殊 loan case、commission、mission reward 和 sick leave 审批。": "Diskaun, kes pinjaman khas, komisen, ganjaran misi dan kelulusan cuti sakit oleh Sales/Admin/Super Admin.",
  "Staff Avatar": "Avatar Kakitangan",
  "共享 staff avatar、staff name badge 和上传式 default avatar library；从 Role Accounts 的 avatar_data_url、default_avatar_id 和 dashboard defaultAvatarLibrary 读取。": "Kongsi avatar kakitangan, lencana nama kakitangan dan pustaka avatar lalai yang dimuat naik; baca daripada avatar_data_url, default_avatar_id dan papan pemuka defaultAvatarLibrary.",
  "Raw lead default message、own tracking link builder、copy full link、copy short link、recent clicks。": "Mesej lalai petunjuk mentah, pembina pautan penjejakan sendiri, salin pautan penuh, salin pautan pendek, klik terkini.",
  "User Profile": "Profil Pengguna",
  "当前 staff avatar 上传、从未被其他 staff 使用的 default avatar library 选择、压缩预览和 role account avatar 保存。": "Muat naik avatar kakitangan semasa, pemilihan pustaka avatar lalai yang tidak pernah digunakan oleh kakitangan lain, pratonton zip dan simpan avatar akaun peranan.",
  "Header 铃铛与面板跟随 Task Inbox 当前单一 Staff scope；badge 显示该员工 scope 对当前查看者的未读通知，Mark all read 也只处理当前 scope。": "Loceng dan panel Pengepala mengikut skop seorang Kakitangan semasa dalam Peti Masuk Tugasan; lencana memaparkan pemberitahuan belum dibaca bagi skop kakitangan itu kepada pemapar semasa dan Tandakan semua dibaca hanya memproses skop semasa.",
  "Search/sort audit entries and changed fields。": "Cari/isih entri audit dan medan yang diubah.",
  "Firebase Repository": "Repositori Firebase",
  "Dashboard state load/save，包括 vehicle categories；250ms queue/pagehide flush 由 persistence hook 管理。": "Muatan/simpan keadaan papan pemuka, termasuk kategori kenderaan; 250ms baris gilir/pagehide flush diurus oleh cangkuk kegigihan.",
  "Excel Customer Import": "Import Pelanggan Excel",
  "默认 dry run；Excel 日期按原始 serial 解码，避免时区造成跨月。恢复缺失资料时使用 --write --missing-only，只新增不存在的 deterministic IDs，不覆盖现有客户。": "Lalai adalah larian kering; Tarikh Excel dinyahkod mengikut siri asal untuk mengelakkan persilangan bulan disebabkan zon waktu. Gunakan --write --missing-only apabila memulihkan data yang hilang. Hanya ID deterministik yang tidak wujud akan ditambahkan dan pelanggan sedia ada tidak akan ditimpa.",
  "scripts/import-loan-applications-from-xlsx.ts": "skrip/import-pinjaman-permohonan-dari-xlsx.ts",
  "Types + Defaults": "Jenis + Lalai",
  "Data model、default banks、vehicles、normalisation rules。": "Model data, bank lalai, kenderaan, peraturan normalisasi.",
  "14. Admin Checklist": "14. Senarai Semak Admin",
  "日常管理时按这个顺序检查，能快速知道系统和业务是否健康。": "Dengan menyemak pesanan ini semasa pengurusan harian, anda boleh mengetahui dengan cepat sama ada sistem dan perniagaan itu sihat.",
  "Morning": "Pagi",
  "先打开 Task Inbox，看当前 staff 今天要处理的 missing info、raw follow-up、bank pending、reminder 和 custom mission progress。": "Mula-mula buka Peti Masuk Tugas dan lihat maklumat yang tiada, susulan mentah, bank belum selesai, peringatan dan kemajuan misi tersuai yang akan dikendalikan oleh kakitangan semasa hari ini.",
  "Mobile Staff": "Kakitangan Bergerak",
  "Sales 在手机上优先打开 Staff View：先处理 due follow-up lead，再用 Call/WhatsApp/Mark Contacted/Next Follow-up 更新状态。": "Jualan membuka Paparan Kakitangan pada telefon mudah alih dahulu: kendalikan petunjuk susulan yang wajar dahulu, dan kemudian gunakan Panggilan/WhatsApp/Tandakan Dihubungi/Susulan Seterusnya untuk mengemas kini status.",
  "导入最新 raw lead CSV，检查 Duplicated numbers；确认错误名单后从 Duplicate Leads 删除，之后导入会自动排除。": "Import CSV prospek mentah terkini dan semak nombor pendua; selepas mengesahkan prospek yang salah, padamkannya daripada Prospek Pendua supaya import seterusnya mengecualikannya secara automatik.",
  "Risk Relationships": "Hubungan Risiko",
  "打开 Potential Customer Relationships，先处理待处理/高风险案件，分配负责人并开始调查；并排核对 phone、IC、bank account、email，记录评论后选择明确结果结案。": "Buka Perhubungan Pelanggan Berpotensi, utamakan kes Belum Diproses/Berisiko Tinggi, tetapkan pemilik dan mulakan siasatan; bandingkan telefon, IC, akaun bank dan e-mel sebelah menyebelah, kemudian catat ulasan dan pilih keputusan yang jelas untuk menutup kes.",
  "Missing Info": "Maklumat hilang",
  "去 Tools > Missing Info Summary，看哪些 staff 未补 New/Used、Cash/Loan 或 File / Document Checklist。": "Pergi ke Alat > Ringkasan Maklumat Hilang untuk melihat kakitangan yang tiada Senarai Semakan Baru/Terpakai, Tunai/Pinjaman atau Fail / Dokumen.",
  "去 Rewards > Payout Center 检查本月 estimated earned、pending review、approved payout；去 Rewards > Missions 检查 custom mission reference data 和 active leaderboard；去 Rewards > Team Battle 检查 team bonus。正式发放必须回到 Approval Workflow。": "Pergi ke Ganjaran > Pusat Pembayaran untuk menyemak anggaran perolehan bulan ini, semakan belum selesai dan pembayaran yang diluluskan; pergi ke Ganjaran > Misi untuk menyemak data rujukan misi tersuai dan papan pendahulu aktif; pergi ke Ganjaran > Pertempuran Pasukan untuk menyemak bonus pasukan. Keluaran rasmi mesti kembali kepada Aliran Kerja Kelulusan.",
  "Bank Follow-up": "Susulan Bank",
  "打开 customer detail，更新 bank application status、need more info、reject/approved decision。": "Buka butiran pelanggan dan kemas kini status permohonan bank, perlukan maklumat lanjut, tolak/luluskan keputusan.",
  "先看 Header 铃铛的 Action Needed。用 Staff Filter 检查负责人的 Bank Need More Info；New raw lead assigned 应由实际 handler 打开并 resolved。": "Mari kita lihat Tindakan Diperlukan pada loceng Pengepala dahulu. Gunakan Penapis Kakitangan untuk menyemak Bank Perlukan Maklumat Lanjut orang yang bertanggungjawab; Petunjuk mentah baharu yang diberikan hendaklah dibuka dan diselesaikan oleh pengendali sebenar.",
  "Rejected Loans": "Pinjaman Ditolak",
  "Final loan REJECT 时必须填至少一个纯数字 CODE；每个 CODE 都要有独立 explanation，全部 CODE chips 会进入 Analytics。Missing Reject Code Explanation 默认隐藏，用户触发后才显示。": "Sekurang-kurangnya satu KOD angka tulen mesti diisi apabila pinjaman akhir TOLAK; setiap KOD mesti mempunyai penjelasan bebas, dan semua cip KOD akan dimasukkan ke dalam Analitis. Penjelasan Kod Tolak yang tiada disembunyikan secara lalai dan akan dipaparkan hanya selepas pengguna mencetuskannya.",
  "Settings": "tetapan",
  "新增 bank、vehicle、source 或 CODE 前先查已有关系。修改车辆分类利率、价格历史、deposit 或 max tenure 后，核对 Monthly Plan；Brand Logo 也从 Setting 统一维护。": "Semak perhubungan sedia ada sebelum menambah bank, kenderaan, sumber atau KOD baharu. Selepas mengubah suai kadar faedah klasifikasi kenderaan, sejarah harga, deposit atau tempoh maksimum, semak Pelan Bulanan; Logo Jenama juga dikekalkan secara seragam daripada Tetapan.",
  "Audit": "Audit",
  "发现数据异常时先看 Tools > Audit Log，确认 staff 和 changed fields。": "Apabila anda menemui anomali data, mula-mula semak Alat > Log Audit untuk mengesahkan kakitangan dan medan yang ditukar.",
  "Sync": "Segerakkan",
  "Header 显示 Firebase error 时，先确认本机仍是 local mode，再处理 Firebase config/rules。": "Apabila Pengepala memaparkan ralat Firebase, mula-mula sahkan bahawa mesin masih dalam mod setempat, dan kemudian proses konfigurasi/peraturan Firebase.",
  "15. Common Issues": "15. Isu Lazim",
  "Admin 遇到问题时先看这些规则。": "Pentadbir harus melihat peraturan ini terlebih dahulu apabila menghadapi masalah.",
  "Question": "soalan",
  "Answer": "Jawab",
  "Where To Check": "Di Mana Untuk Semak",
  "为什么 customer 没有出现在某个 staff 视图？": "Mengapa pelanggan tidak muncul dalam pandangan kakitangan?",
  "Customers 默认按 staff scope；确认 handler_name 是否等于当前登录 staff，或 Super Admin 是否开启 Show All。": "Pelanggan lalai kepada skop kakitangan; sahkan sama ada nama_pengendali adalah sama dengan kakitangan yang sedang log masuk atau sama ada Pentadbir Super telah menghidupkan Tunjukkan Semua.",
  "Customers top staff scope card。": "Kad skop kakitangan teratas pelanggan.",
  "Roles & Accounts 的 Add Account 会通过受保护 backend API 创建或连接 Firebase Auth user；连接已存在 user 时不会改旧密码。要改密码，用该账号 row 的钥匙按钮重置 Firebase password。必须用 Firebase Auth Super Admin 登录。": "Tambah Akaun Peranan & Akaun akan membuat atau menyambungkan pengguna Firebase Auth melalui API bahagian belakang yang dilindungi; kata laluan lama tidak akan ditukar apabila menyambung kepada pengguna sedia ada. Untuk menukar kata laluan anda, gunakan butang kekunci baris akaun untuk menetapkan semula kata laluan Firebase. Mesti log masuk dengan Pentadbir Super Firebase Auth.",
  "Setting > Roles & Accounts / Firebase Authentication。": "Tetapan > Peranan & Akaun / Pengesahan Firebase.",
  "为什么 Missing Info 一直出现？": "Mengapa Maklumat Hilang terus muncul?",
  "该 customer 缺 New/Used、Cash/Loan 或 File / Document Checklist 里仍有 Missing 文件，且 handler 是当前 staff。补齐后 missing info 会消失。": "Pelanggan masih mempunyai fail Hilang dalam Senarai Semak Baru/Terpakai, Tunai/Pinjaman atau Fail/Dokumen, dan pengendali adalah kakitangan semasa. Maklumat yang hilang akan hilang selepas selesai.",
  "Tools > Missing Info Summary。": "Alat > Ringkasan Maklumat Tiada.",
  "为什么上传后 checklist 自动变 Received？": "Mengapa senarai semak bertukar secara automatik kepada Diterima selepas memuat naik?",
  "每个 File / Document Checklist item 都有自己的 upload button。该 item 有文件后系统自动视为 Received；没有文件时用户只能手动选择 Missing 或 Not Required。": "Setiap item Senarai Semak Fail / Dokumen mempunyai butang muat naik sendiri. Apabila item mempunyai fail, sistem secara automatik menganggapnya sebagai Diterima; apabila tiada fail, pengguna hanya boleh memilih Hilang atau Tidak Diperlukan secara manual.",
  "Customer Detail Drawer > File / Document Checklist。": "Laci Butiran Pelanggan > Senarai Semak Fail/Dokumen.",
  "Custom Mission 的进度怎么算？": "Bagaimanakah kemajuan Misi Tersuai dikira?",
  "Top Sales 算 approved loan，Fast Response 算 taken lead 到 first follow-up 的平均分钟，Raw Lead Conversion 算 taken lead 是否匹配到 customer application。": "Jualan Tertinggi dikira sebagai pinjaman yang diluluskan, Respons Pantas dikira sebagai purata minit dari petunjuk yang diambil kepada susulan pertama, dan Penukaran Petunjuk Mentah dikira sama ada petunjuk yang diambil sepadan dengan aplikasi pelanggan.",
  "为什么 30 天以前的贷款资料不见了？": "Mengapa maklumat pinjaman lebih lama daripada 30 hari hilang?",
  "Customers 和 8 张 cards 默认只统计最近 30 个 calendar days，旧资料没有被删除。由用户把 time filter 切到 All time 或选择自定义日期。": "Pelanggan dan 8 kad hanya mengira 30 hari kalendar terakhir secara lalai dan data lama tidak dipadamkan. Terpulang kepada pengguna untuk menukar penapis masa kepada Sepanjang masa atau memilih tarikh tersuai.",
  "Customers time filter。": "Penapis masa pelanggan.",
  "为什么 Staff View 没有某个 lead？": "Mengapa Staff View tidak mempunyai petunjuk tertentu?",
  "Staff View 只显示当前 staff 自己 taken 的 lead；确认 raw lead 的 taken_by_staff_name 是否等于当前登录 staff。": "Paparan Kakitangan hanya memaparkan petunjuk yang diambil oleh kakitangan semasa; sahkan sama ada nama_kakitangan_yang diambil bagi petunjuk mentah adalah sama dengan kakitangan yang sedang dilog masuk.",
  "Raw Customers / Follow Up。": "Pelanggan Mentah/Susulan.",
  "为什么 Sales 的 Analytics 数字比 Admin 少？": "Mengapakah Jualan mempunyai lebih sedikit nombor Analitis daripada Pentadbir?",
  "Sales Analytics 是 personal scope，只统计自己的 customers、taken raw leads、WhatsApp links/clicks 和自己的 role account。Admin/Super Admin 才看 all-staff analytics。": "Analitis Jualan ialah skop peribadi dan hanya mengira pelanggan anda sendiri, mengambil petunjuk mentah, pautan/klik WhatsApp dan akaun peranan anda sendiri. Pentadbir/Pentadbir Super hanya melihat analisis semua kakitangan.",
  "Tools > Analytics scope badge。": "Alat > Lencana skop Analitis.",
  "为什么新增 Role Account 后 Firebase 没有用户或密码没变？": "Mengapakah Firebase tidak mempunyai perubahan pengguna atau kata laluan selepas menambah Akaun Peranan baharu?",
  "Rewards > Missions。": "Ganjaran > Misi.",
  "创建 Custom Mission 前怎样决定 target？": "Bagaimana untuk menentukan sasaran sebelum membuat Misi Tersuai?",
  "打开 New Mission 后看 Reference Data。它会根据当前 metric、timeframe、scope 显示 staff 现有表现和 current leader。": "Buka Misi Baharu dan lihat Data Rujukan. Ia akan memaparkan prestasi semasa kakitangan dan pemimpin semasa berdasarkan metrik, jangka masa dan skop semasa.",
  "Rewards > Missions > Custom Mission Builder。": "Ganjaran > Misi > Pembina Misi Tersuai.",
  "为什么 Reward Center 金额还没变成 Approved？": "Mengapakah jumlah Pusat Ganjaran tidak berubah kepada Diluluskan?",
  "Reward Center 先显示从现有数据推算的 earned/estimate。真正发放必须在 Approval Workflow 提交并审核，审核后才会显示 Approved/Pending。": "Pusat Ganjaran terlebih dahulu memaparkan perolehan/anggaran yang diperoleh daripada data sedia ada. Keluaran sebenar mesti diserahkan dan disemak dalam Aliran Kerja Kelulusan, dan Diluluskan/Belum selesai akan dipaparkan hanya selepas semakan.",
  "Rewards + Tools > Approvals。": "Ganjaran + Alat > Kelulusan.",
  "为什么银行跟进没有出现在 Calendar/Task Inbox？": "Mengapa susulan bank tidak muncul dalam Kalendar/Peti Masuk Tugas?",
  "银行提醒不单独存表。需要在 Bank Application 填 Bank Follow Up Date，到期后才会出现在 Calendar、Task Inbox 和 Notification。": "Peringatan bank tidak disimpan dalam jadual berasingan. Isi Tarikh Susulan Bank dalam Permohonan Bank; selepas tiba masanya, peringatan akan muncul dalam Kalendar, Peti Masuk Tugas dan Pemberitahuan.",
  "Customer Detail Drawer > Bank Applications。": "Laci Butiran Pelanggan > Permohonan Bank.",
  "Customer Detail Drawer。": "Laci Butiran Pelanggan.",
  "为什么 Notification badge 和 Task Inbox 数量不同？": "Mengapakah lencana Pemberitahuan dan nombor Peti Masuk Tugas berbeza?",
  "铃铛 badge 计算当前 staff scope 的 unread notifications；Task Inbox card 计算当前 scope 的 active tasks。一个是阅读状态，一个是待办状态，因此不要求相同。": "Lencana loceng mengira pemberitahuan belum dibaca bagi skop kakitangan semasa; kad Peti Masuk Tugas mengira tugas aktif skop semasa. Satu adalah keadaan membaca dan satu lagi adalah keadaan tugasan, jadi mereka tidak perlu sama.",
  "Header Notification Center + Task Inbox Staff Filter。": "Pusat Pemberitahuan Pengepala + Penapis Kakitangan Peti Masuk Tugas.",
  "为什么 New raw lead assigned 一直出现？": "Mengapa petunjuk mentah baharu yang diberikan terus muncul?",
  "它只应在实际 take/transfer 时创建一次。handler 打开后 resolved；release 会移除，重新 take 才创建新事件。若 Super Admin 只是在别人的 scope 查看，不会替 handler resolved。": "Ia hanya perlu dibuat sekali untuk pengambilan/pemindahan sebenar. Selepas pengendali dibuka, ia diselesaikan; keluaran akan dialih keluar dan acara baharu akan dibuat selepas mengambil semula. Jika Pentadbir Super hanya melihat dalam skop orang lain, ia tidak akan diselesaikan untuk pengendali.",
  "Raw Customers + Notification Center。": "Pelanggan Mentah + Pusat Pemberitahuan.",
  "为什么 bank selection 没有某间银行？": "Mengapa tidak ada bank tertentu dalam pemilihan bank?",
  "Bank Database 里该 bank 可能 inactive 或未创建。": "Bank dalam Pangkalan Data Bank mungkin tidak aktif atau tidak dibuat.",
  "Setting > Bank Database。": "Tetapan > Pangkalan Data Bank.",
  "为什么 Analytics source 很乱？": "Mengapakah sumber Analitis begitu berantakan?",
  "System Manual > Brand / UIUX Guide。": "Manual Sistem > Jenama / Panduan UIUX.",
  "为什么 Firebase error？": "Mengapa ralat Firebase?",
  "Dashboard 会先用 localStorage 继续运行。需要检查 .env.local、Firestore rules 或 network。": "Papan pemuka akan terus berjalan menggunakan localStorage terlebih dahulu. Perlu menyemak .env.local, peraturan atau rangkaian Firestore.",
  "Header sync badge + browser console。": "Lencana penyegerakan pengepala + konsol penyemak imbas.",
  "Main Rule": "Peraturan Utama",
  "Admin/Sales 尽量输入真实业务资料；系统负责 normalisation、matching、audit 和 reporting。Raw leads 不直接变 Customers；customer 不填写 staff-only purchase fields；Setting 是业务规则来源；Tools 是 reporting/tracking/audit；所有重要修改都应该能在 Audit Log 找到。": "Pentadbir/Jualan cuba memasukkan maklumat perniagaan sebenar; sistem bertanggungjawab untuk normalisasi, pemadanan, audit dan pelaporan. Petunjuk mentah tidak bertukar terus kepada Pelanggan; pelanggan tidak mengisi medan pembelian kakitangan sahaja; Penetapan adalah sumber peraturan perniagaan; Alat sedang membuat laporan/penjejakan/audit; semua pengubahsuaian penting hendaklah ditemui dalam Log Audit.",
  "Marketing source 没有 normalisation rule，或 parent/category 被重复创建。": "Sumber pemasaran tidak mempunyai peraturan normalisasi atau induk/kategori dibuat berulang kali.",
  "Setting > Debug Data Cleanup > Data Cleanup。": "Tetapan > Nyahpepijat Pembersihan Data > Pembersihan Data.",
  "为什么 rejected code 没有说明或数量不对？": "Mengapa tiada penerangan atau nombor yang salah untuk kod yang ditolak?",
  "Bank Database 的 Reject Reason Codes 必须为纯数字 code 加 explanation；final status 为 REJECT 时，每个 code 独立匹配一个解释。Missing Reject Code Explanation 默认隐藏，点击 Show missing explanations 才展开。": "Kod Sebab Tolak Pangkalan Data Bank mestilah kod angka tulen serta penjelasan; apabila status akhir adalah TOLAK, setiap kod secara berasingan sepadan dengan penjelasan. Penjelasan Kod Tolak yang tiada disembunyikan secara lalai dan akan dikembangkan apabila anda mengklik Tunjukkan penjelasan yang tiada.",
  "Setting > Bank Database + Customers final status。": "Tetapan > Pangkalan Data Bank + Status akhir pelanggan.",
  "为什么 Vehicle Monthly Plan 跟预期不同？": "Mengapakah Rancangan Bulanan Kenderaan berbeza daripada yang dijangkakan?",
  "检查车型 category、计算日期对应的 effective rate、当时有效的 loan amount/deposit price history、finance profile，以及 model max tenure/category default tenure。": "Semak kategori kenderaan, kadar berkesan sepadan dengan tarikh pengiraan, jumlah pinjaman/sejarah harga deposit, profil kewangan dan model tempoh maks/kategori tempoh lalai yang berkuat kuasa pada masa itu.",
  "Setting > Vehicle Categories / Vehicle Info。": "Tetapan > Kategori Kenderaan / Maklumat Kenderaan.",
  "为什么 Dark Mode 的状态颜色看起来不对？": "Mengapa warna status Mod Gelap kelihatan salah?",
  "状态必须使用语义色：amber pending、purple follow-up、emerald success、rose/red reject、blue/indigo info。若某个组件硬编码浅色背景，需要按这套规则修正，而不是加 card outline。": "Status mesti menggunakan warna semantik: ambar belum selesai, susulan ungu, kejayaan zamrud, penolakan mawar/merah, maklumat biru/indigo. Jika komponen mempunyai latar belakang cahaya berkod keras, ia perlu diperbetulkan mengikut set peraturan ini dan bukannya menambah rangka kad."
};
